### ISSUE TITLE
Under M1 Mac, system to crash and restart.

### ISSUE THREAD

**Issue by eoogo** [bettercap/bettercap#836] opened 2021-02-22 14:06 UTC
### Environment

Bettercap version: bettercap v2.29 (built for darwin arm64 with go1.16rc1)
OS version: MacOS Big Sur 11.2.1 (M1)
Go version: go version go1.16rc1 darwin/arm64

### Steps to Reproduce

When using wifi.ap or wifi.deauth

Under M1 Mac, the wifi.ap or wifi.deauth module will cause the system to crash and restart.
Will this issue be resolved in the update?

**Comment by buffermet** [comment] 2021-02-24 19:08
Probably a duplicate of https://github.com/bettercap/bettercap/issues/448

**Closed** 2021-02-24 19:08 UTC
