### ISSUE TITLE
UI PROBLEM

### ISSUE THREAD

**Issue by luiznfbr2** [bettercap/bettercap#1159] opened 2024-12-01 22:23 UTC
Can't get Bettercap UI working.
Cant get API rest Working

### Environment

* Bettercap version (bettercap v2.32.0 (built for linux arm64 with go1.19.8)
* Description:    Debian GNU/Linux 12 (bookworm) - 6.6.51+rpt-rpi-v8
* Go version go1.19.8 linux/arm64 
* RaspberryOS Lite x64
*Raspberry PI W2

*sudo bettercap -caplet http-ui bettercap*

installed by apt install bettercap

- My screen shots
![image](https://github.com/user-attachments/assets/b7e2cdeb-23fb-458c-9c92-50a120730e96)
-
![image](https://github.com/user-attachments/assets/6fdcfa50-9091-409d-812a-bbcbba111f73)
frontend dosent work any ideas?
-- 
![image](https://github.com/user-attachments/assets/528892b4-edbf-447e-83c0-b050f48d8fbe)
--
![image](https://github.com/user-attachments/assets/a0dbbd81-b884-4f9d-adac-dd9056806236)
--
With the Pwnagotchi project, it worked correctly, but I couldn't access the information via the API.  
As I'm working on another project, I installed the Pi OS Lite 64x and really tried installing it in every possible way—third-party scripts, Go versions—but without success. I even just spent my Sunday dealing with this situation.  
I need a little help from the community.  
Thank you, and remember: I'm just starting, but I'm dreaming big with these amazing tools.  
Thank you.

**Comment by buffermet** [comment] 2024-12-02 20:08
> installed by apt install bettercap

This seems to be a duplicate of https://github.com/bettercap/bettercap/issues/992

You can find a proposed solution there.

**Closed by buffermet** 2024-12-02 20:08 UTC
