### ISSUE TITLE
hcxpcapngtool expired for hcxpcapngtool no Bettercap .pcapng format?

### ISSUE THREAD

**Issue by gateway** [bettercap/bettercap#810] opened 2021-01-11 20:36 UTC
*Description of the bug or feature request*

### Environment

Please provide:

* Bettercap version you are using 2.28
* MacOS Catalina
* 14.4
* `sudo bettercap -iface wlp0s20f0u2 -caplet pwnagotchi.cap`
* 
```
# set wifi.recon.channel 1,2,3,4,5,6,7,8,9,11,12
# set wifi.region 00
set ticker.period 20
set ticker.commands clear; wifi.show; wifi.assoc all; sleep 7; wifi.deauth all
wifi.recon on
sleep 5
ticker on
events.ignore wifi.client.probe
events.clear
clear
```
It seems that https://github.com/ZerBea/hcxtools has removed hcxpcaptool for hcxpcapngtool which the pcapng file format is needed.  From my tests of taking a bettercap.pcap file and trying to convert it the results are posted below, but here is my concern..

`
hcxpcapngtool | Provide new hashcat format 22000
`

`Warning: out of sequence timestamps!
This dump file contains frames with out of sequence timestamps.
That is a bug of the capturing tool.

Warning: missing frames!
This dump file does not contain undirected proberequest frames.
An undirected proberequest may contain information about the PSK.
It always happens if the capture file was cleaned or
it could happen if filter options are used during capturing.
That makes it hard to recover the PSK.`

**Actual behavior:** *What actually happened*

-- 

```
hcxpcapngtool -o local.pmkid better bc.pcap
failed to open file: No such file or directory
reading from bc.pcap...

summary capture file
--------------------
file name................................: bc.pcap
version (pcap/cap).......................: 2.4 (very basic format without any additional information)
timestamp minimum (GMT)..................: 11.01.2021 11:09:06
timestamp maximum (GMT)..................: 11.01.2021 11:47:46
used capture interfaces..................: 1
link layer header type...................: DLT_IEEE802_11_RADIO (127)
endianess (capture system)...............: little endian
packets inside...........................: 325
frames with correct FCS..................: 325
BEACON (total)...........................: 193
PROBERESPONSE............................: 5
REASSOCIATIONREQUEST (total).............: 1
REASSOCIATIONREQUEST (PSK)...............: 1
EAPOL messages (total)...................: 126
EAPOL RSN messages.......................: 126
ESSID (total unique).....................: 9
EAPOLTIME gap (measured maximum usec)....: 5524
EAPOL ANONCE error corrections (NC)......: not detected
EAPOL M1 messages (total)................: 124
EAPOL M2 messages (total)................: 1
EAPOL M3 messages (total)................: 1
EAPOL pairs (total)......................: 2
EAPOL pairs (best).......................: 1
EAPOL pairs written to combi hash file...: 1 (RC checked)
EAPOL M32E2 (authorized).................: 1
PMKID (total)............................: 3
PMKID (best).............................: 3
PMKID written to combi hash file.........: 3

Warning: out of sequence timestamps!
This dump file contains frames with out of sequence timestamps.
That is a bug of the capturing tool.

Warning: missing frames!
This dump file does not contain undirected proberequest frames.
An undirected proberequest may contain information about the PSK.
It always happens if the capture file was cleaned or
it could happen if filter options are used during capturing.
That makes it hard to recover the PSK.


session summary
---------------
processed cap files...................: 1
```

Does Bettercap support the new format for 22000? Am I missing a simple step ?

from the readme of hcxtools 

`Support for hashcat hash-modes: 4800, 5500, 2200x, 16100, 250x (deprecated), 1680x (deprecated)`

Thoughts?

**♥ ANY INCOMPLETE REPORT WILL BE CLOSED RIGHT AWAY ♥**

**Comment by evilsocket** [comment] 2021-03-14 15:36
unfortunately the format changed and i never had the time to do the necessary updates :/

**Comment by ZerBea** [comment] 2021-03-14 16:23
Some additional basic information:
Starting on 16.12.2019 hcxpcapngtool replaced hcxpcaptool.
Main changes:
moved to pcapng as default format (according to Wireshark and tshark)
https://www.wireshark.org/docs/wsug_html_chunked/ChIOOpenSection.html

now using  Authentication Key Management (AKM) to identify EAPOL messages and PMKIDs

moved to hash format 22000 (according to hashcat) to get full advantage of reuse of PBKDF2 over PMKID and EAPOL
https://github.com/hashcat/hashcat/issues/1816


Notice about the warnings:
```
Warning: missing frames!
This dump file does not contain undirected proberequest frames.
An undirected proberequest may contain information about the PSK.
It always happens if the capture file was cleaned or
it could happen if filter options are used during capturing.
That makes it hard to recover the PSK.
```
bettercap doesn't store important frames, from which we can get the PSK in the clear or more PMKIDs, or the AKM of the PMKIDs:
undirected PROBEREQUEST frames
ASSOCIATIONREQUEST frames
REASSOCIATIONREQUST frames
EAP ID frames
This issue was reported here:
https://github.com/evilsocket/pwnagotchi/issues/835

```
Warning: out of sequence timestamps!
This dump file contains frames with out of sequence timestamps.
That is a bug of the capturing tool.
```
The timestamps are not in the chronological order in which they have been received. Sometimes an EAPOL M2 is stored before an EAPOL M1. 
This issue was reported here:
https://github.com/evilsocket/pwnagotchi/issues/880

Cheers
Mike

**Comment by evilsocket** [comment] 2021-03-14 17:00
Thanks a lot @ZerBea! 

PcapNG is not entirely supported by gopacket yet, so switching to that format would involve a massive effort, not sure it's worth it if we can achieve the same results with pcap.

Can you elaborate a bit what you mean with undirected proberequest frames? You are referring to PROBEREQUESTs sent by clients to test for the presence of an AP right? What do you mean with undirected? And should bettercap store all those frames you've mentioned for every client or ... ?

Regarding the timestamp issue, did you see it anywhere other than pwnagotchi (like [here](https://github.com/evilsocket/pwnagotchi/issues/880))? i'm asking because those units don't have a RTC by default, so any timer would be messed up. I think that normal captures coming from more advanced boards have correct timestamps.

**Comment by ZerBea** [comment] 2021-03-14 20:46
hcxdumptool moved to pcapng format because we need to transport additional information like
attack MAC AP
attack MAC CLIENT
attack REPLAYCOUNT
attack ANONCE
attack SNONCE
and some more fields.
cap and pcap don't satisfy this.

directed PROBEREQUEST:
to MAC AP from real MAC CLIENT using AP ESSID

undirected PROBEREQUST
to BROADCAST MAC (ff:ff:ff:ff:ff:ff:) from MAC CLIENT (that inlcude randomized MAC)
you should have received 3 examples vie PM.

Yes, I saw several other tools other than pwnagotchi. Airodump-ng was among them:
https://github.com/aircrack-ng/aircrack-ng/issues/2169#issuecomment-665707380
The issue is independent of the RTC.
hcxdumptool was running into that issue (on every system), too until I fixed it by this commit:
https://github.com/ZerBea/hcxdumptool/commit/f6834addce416f012a5503e6902c47a183cdf546

**Comment by ZerBea** [comment] 2021-03-14 20:49
BTW:
It is far from enough to store only a single BEACON.
A BEACON contain all supported CIPHER SUITES and AKM SUITES, but only the ASSOCIATIONREQUEST and REASSOCIATIONREQUEST contain CIPHER and AKM SUITE which is in use for the ASSOCIATION.
On EAP (e.g. SAE) we need additional the AUTHENTICATION frames 1,2,3,4, too.

**Comment by evilsocket** [comment] 2021-03-14 20:50
mmm it seems to me that it's just more convenient to save everything but data packets ... would that work or without pcapng support it wouldn't work anyway?

**Comment by ZerBea** [comment] 2021-03-14 20:58
Yes, for sure it will work. You don't need to use pcapng format.
For me the reason to use pcapng is within the whole chain:
hcxdumptool save all additional attack parameters to pacpng
hcxpcapngtool use this parameters to identify the correct hash and prepare it for hashcat (store the attack information within MESSAGE PAIR filed)
hashcat use this message pair information to improve it's cracking process

or simple explained:
`hcxdumptool (pcapng comment filed) -> hcxpcapngtool (message pair field) -> hashcat (using messagapair field to improve attack)
`

**Comment by ZerBea** [comment] 2021-03-15 07:57
@gateway , can you please attach the cap file. That will help @evilsocket to identify the timestamp issue within timestamp handling of bettercap. It looks like some frames are either enqueued (by internal ringbuffer) or delivered with a wrong timestamp.

**Comment by ZerBea** [comment] 2021-03-15 08:23
@evilsocket , please take a look at hcxdumptool's association/reassociation attack vector. It is more powerful that running stupid deauthentications (expecially if MFP is in use).
Please also take a look at hcxdumptools M4 attack. In case we received only a single M4, hcxdumptool request the whole AUTHENTICATION sequence again.
Please also take a look at hcxdumptool's EAP attack vector to request an EAP ID.

**Comment by evilsocket** [comment] 2021-03-23 18:46
@ZerBea man i don't know if you realize how dense your C code is :'D i don't think i'll be able to replicate the more advanced attacks in golang in any reasonable amount of time :'D especially considering the lack of gopacket support for some Dot11 things it'd be a gigantic effort ... as a first step it'd be nice to make the handshakes good for cracking again :D

I was thinking about a possible approach, tell me what you think about it ... the conditions i should check in order to save frames are many, what if, once i have the handshake basic frames (when once of these conditions is true https://github.com/bettercap/bettercap/blob/master/modules/wifi/wifi_recon_handshakes.go#L109), i just start dumping on the pcap everything from or to that AP-client that is not data. Does that work? I mean, is there something I might miss happening BEFORE those conditions are met that won't be retransmitted again afterwards? I'm looking at low hanging fruits here.

**Comment by ZerBea** [comment] 2021-03-24 07:38
Your approach is good, but it is slow . Unfortunately there is nothing you can do about it. Its is a long way for an incoming packet, before bettercap can check the conditions: WiFi device -> driver -> libnl (NETLINK) -> libpcap -> gofile -> bettercap)

A good idea is:
Save all EAPOL and EAP frames to pcap.
Save all AUTHENTICATION frames to pcap.
Save all ASSOCIATION and REASSOCIATION frames to pacap.
Save all PROBEREQUEST frames to pcap
Save all PROBERESPONSE frames to pacap
Save a single BEACON to pcap - not mandatory, if we got all above frames.

If you decide to allow the user to upload the dumpfile to e.g.: wpa-sec, copress it by gzip.
Nearly all state of the art tool (Wireshark, tshark, hcxtools) is able to read a gzip compressed cap/pcap/pcapng dump file.

At this point, a conversion tool will get all information to calculate a valid EAPOL message pair or to get the PMKID (from M1 or M2 or REASSOCIATION frames. 

Next step is to satisfy the bettercap user. I assume the user would like to see a "beautiful status" that he captured a handshake or a PMKID. Unfortunately, this makes us slow, again.
A good approach is to do this, after you stored the frames.
You can do it by a ring buffer of at least 20000usec. Just store EAPOL messages to this buffer.
If you receive an EAPOL M2 go back in time and look for an M1 that have the same REPLAYCOUNT and is not older than 20000usec.
If you receive an EAPOL M3 go back in time and look for an M2 that have the REPLAYCOUNT -1 and is not older than 20000usec.
If you receive an EAPOL M4 with a non-zeroed SNONCE go back in time and look for an M3 that have the same REPLAYCOUNT and is not older than 20000usec.
If you got no matching pair: send DEAUTHENTICATION wit reason code WLAN_REASON_DISASSOC_AP_BUSY.

The timestamp problem is more complex, because (I assume) gofile use libpcap and NETLINK. All packets are enqueued. That lead to some strange timestamp behavior.

The attacks are not as hard as it looks:
If you receive an ACTION, BLK or NULL frame from a CLIENT, just send a REASSOCIATIONREQUEST frame to the AP.
Or as mentioned above:
If you receive an EAPOL M4 frame, just send a DEAUTHENTICATION frame with reason code
WLAN_REASON_DISASSOC_AP_BUSY.


BTW:
I admire you, coding such complex things in gofile. That is very difficult (libnl dependency, libpcap dpendency).

**Comment by evilsocket** [comment] 2021-03-24 10:08
I'll start working on the first iteration ASAP. My first goal is being able to align with what hcxpcapngtool needs again. Then i'll go for a second pass of optimizations and improvements :D

Difficult but nevertheless fun! :D After years spent coding in C and C++ go is a very refreshing change, you should try :D

**Comment by ZerBea** [comment] 2021-03-24 11:17
hcxpcapngtool doesn't need much
Duty:
ESSID, M1 and M2 from cap, pcap or pcapng dump files (gz compression is supported)

Choice:
PROBEREQUESTs, PROBERESPONSE, AUTHENTICATION, ASSOCIATIONREQUEST, REASSOCIATIONREQUEST, M1, M2, EAP-ID

Default output is hash format 22000 due to many advantages (2500, 16800, john are supported) and several useful lists (-EIU) of which default PSKs can be calculated (e.g. in combination with rules).

BTW:
C is my refresh. I'm an ASM coder.

**Comment by evilsocket** [comment] 2021-03-24 11:18
give it time :'D

**Comment by evilsocket** [comment] 2021-03-30 21:31
@ZerBea great success!!! the very simple heuristic i've mentioned seems to be working, at least according to the output of your tool now:

```
reading from bettercap-wifi-handshakes.pcap...

summary capture file
--------------------
file name................................: bettercap-wifi-handshakes.pcap
version (pcap/cap).......................: 2.4 (very basic format without any additional information)
timestamp minimum (GMT)..................: 30.03.2021 23:23:57
timestamp maximum (GMT)..................: 30.03.2021 23:24:39
used capture interfaces..................: 1
link layer header type...................: DLT_IEEE802_11_RADIO (127)
endianess (capture system)...............: little endian
packets inside...........................: 209
BEACON (total)...........................: 55
ACTION (total)...........................: 10
PROBEREQUEST.............................: 3
PROBERESPONSE............................: 16
AUTHENTICATION (total)...................: 1
AUTHENTICATION (OPEN SYSTEM).............: 1
ASSOCIATIONREQUEST (total)...............: 21
ASSOCIATIONREQUEST (PSK).................: 21
EAPOL messages (total)...................: 102
EAPOL RSN messages.......................: 102
ESSID (total unique).....................: 3
EAPOLTIME gap (measured maximum usec)....: 569109
EAPOL ANONCE error corrections (NC)......: not detected
EAPOL M1 messages (total)................: 92
EAPOL M2 messages (total)................: 4
EAPOL M3 messages (total)................: 4
EAPOL M4 messages (total)................: 2
EAPOL pairs (total)......................: 52
EAPOL pairs (best).......................: 2
EAPOL pairs written to combi hash file...: 2 (RC checked)
EAPOL M32E2 (authorized).................: 2

Warning: out of sequence timestamps!
This dump file contains frames with out of sequence timestamps.
That is a bug of the capturing tool.


session summary
---------------
processed cap files...................: 1
```

There's still the timestamps issue, but that is due to how the packets are serially dumped to disk. In order to fix that I should reload the entire pcap at each saving operation, sort the frames and redump it sorted ... just too heavy, and as you mentioned the driver timestamp can't be trusted anyway. What do you think, can we close this issue since the missing frames error is fixed?

**Comment by ZerBea** [comment] 2021-03-30 23:14
Excellent work! Now hcxpcapngtool can retrieve possible PSKs, running -E option.
For me, the missing frames issue is fixed.

About the timestamp issue:
hcxdumptool serially dump to file like bettercap, but  it ignore the timestamp reported by the driver.
Instead it get the current actual system time and store this timestamp for the received packet.
Result is that all packets are in sequence with incremented timestamp.

Cheers
Mike

**Closed** 2021-03-30 23:30 UTC
Labels: bug, help wanted
