### ISSUE TITLE
bettercap collects logins and passwords not from all HTTP!

### ISSUE THREAD

**Issue by torerobo** [bettercap/bettercap#313] opened 2018-08-15 16:00 UTC
1.I ran both Bettercap and Ettercap (G) at the same time.
[http://vyazniki-extreme.ru/forum/?do=search](http://vyazniki-extreme.ru/forum/?do=search)
I turn to the http site, enter the data and both programs capture them
![1](https://user-images.githubusercontent.com/35532898/44158231-e620b880-a0bc-11e8-89d2-bbda10afe258.png)

2.In this HTTP it worked.
I go to another HTTP site.
[http://www.banki.ru/auth/?login=yes](http://www.banki.ru/auth/?login=yes)
I enter any login and password. In Ettercap, I see my login and password. The bettercap is empty.
![2](https://user-images.githubusercontent.com/35532898/44158393-3a2b9d00-a0bd-11e8-843c-4215ca27520f.png)

Please check and see for yourself.

bettercap V2.7

**Comment by saikishorekate** [comment] 2018-08-17 05:43
Yes please do that!
Same problem occurring!

**Comment by evilsocket** [comment] 2018-08-17 13:06
can't reproduce as banki.ru has hsts rules and it's using https, how did you get it working on http?

**Comment by evilsocket** [comment] 2018-08-20 13:34
no feedback in 3 days, closing

**Closed by evilsocket** 2018-08-20 13:34 UTC
