### ISSUE TITLE
Can't monitor Wi-Fi connection on Windows 10 x64 - "No Interface matching 'Wi-Fi' found"

### ISSUE THREAD

**Issue by mydockergit** [bettercap/bettercap#431] opened 2019-02-03 15:31 UTC
*Description of the bug or feature request*
I am trying to monitor an Android application with Windows 10.  
I ran `bettercap -iface "Wi-Fi"` to monitor the Wi-Fi connection.  
I received this error:  
```
C:\tmp>bettercap -iface "Wi-Fi"

WARNING: This terminal does not support colors, view will be very limited.

bettercap v2.13.1 (type 'help' for a list of commands)

No interface matching 'Wi-Fi' found.
```
How can I know what is the correct Wi-Fi interface name ? 

### Environment

Please provide:

* Bettercap version you are using. -> v2.13.1
* OS version and architecture you are using. -> Windows 10 x64
* Go version if building from sources. ->  go1.11 windows/amd64
* Command line arguments you are using. -> `bettercap -iface "Wi-Fi"`
* Caplet code you are using or the interactive session commands. -> None
* **Full debug output** while reproducing the issue ( `bettercap -debug ...` ).
```
C:\tmp>bettercap -debug


WARNING: This terminal does not support colors, view will be very limited.

bettercap v2.13.1 (type 'help' for a list of commands)

[17:25:47] [sys.log] [dbg] FindGateway(\Device\NPF_{66CA340E-5382-479F-92BB-26768203D903}) [cmd=netsh opts=[interface ipv4 show route] parser=^.+\s+.+\s+\d+\s+([0-9\.]+/\d+)\s+\d+\s+([0-9\.]+).*$]
[17:25:47] [sys.log] [dbg] FindGateway(\Device\NPF_{66CA340E-5382-479F-92BB-26768203D903}) output:
Publish  Type      Met  Prefix                    Idx  Gateway/Interface Name
-------  --------  ---  ------------------------  ---  ------------------------
No       Manual    0    0.0.0.0/0                  28  10.0.63.254
No       System    256  10.0.60.0/22               28  Wi-Fi
No       System    256  10.0.62.158/32             28  Wi-Fi
No       System    256  10.0.63.255/32             28  Wi-Fi
No       System    256  127.0.0.0/8                 1  Loopback Pseudo-Interface 1
No       System    256  127.0.0.1/32                1  Loopback Pseudo-Interface 1
No       System    256  127.255.255.255/32          1  Loopback Pseudo-Interface 1
No       System    256  169.254.0.0/16             24  VMware Network Adapter VMnet8
No       System    256  169.254.64.206/32          24  VMware Network Adapter VMnet8
No       System    256  169.254.255.255/32         24  VMware Network Adapter VMnet8
No       System    256  192.168.0.0/24             20  VMware Network Adapter VMnet2
No       System    256  192.168.0.1/32             20  VMware Network Adapter VMnet2
No       System    256  192.168.0.255/32           20  VMware Network Adapter VMnet2
No       System    256  192.168.21.0/24            27  VirtualBox Host-Only Network #2
No       System    256  192.168.21.1/32            27  VirtualBox Host-Only Network #2
No       System    256  192.168.21.255/32          27  VirtualBox Host-Only Network #2
No       System    256  224.0.0.0/4                 1  Loopback Pseudo-Interface 1
No       System    256  224.0.0.0/4                27  VirtualBox Host-Only Network #2
No       System    256  224.0.0.0/4                 9  Local Area Connection* 3
No       System    256  224.0.0.0/4                10  Bluetooth Network Connection
No       System    256  224.0.0.0/4                28  Wi-Fi
No       System    256  224.0.0.0/4                25  Local Area Connection* 5
No       System    256  224.0.0.0/4                13  Local Area Connection* 7
No       System    256  224.0.0.0/4                20  VMware Network Adapter VMnet2
No       System    256  224.0.0.0/4                24  VMware Network Adapter VMnet8
No       System    256  255.255.255.255/32          1  Loopback Pseudo-Interface 1
No       System    256  255.255.255.255/32         27  VirtualBox Host-Only Network #2
No       System    256  255.255.255.255/32          9  Local Area Connection* 3
No       System    256  255.255.255.255/32         10  Bluetooth Network Connection
No       System    256  255.255.255.255/32         28  Wi-Fi
No       System    256  255.255.255.255/32         25  Local Area Connection* 5
No       System    256  255.255.255.255/32         13  Local Area Connection* 7
No       System    256  255.255.255.255/32         20  VMware Network Adapter VMnet2
No       System    256  255.255.255.255/32         24  VMware Network Adapter VMnet8
[17:25:47] [mod.started] net.recon
[17:25:47] [sys.log] [war] Could not detect gateway.
169.254.0.0/16 > 169.254.35.159  » [17:25:47] [session.started] {session.started 2019-02-03 17:25:47.4661736 +0200 IST m=+0.626966401 <nil>}
169.254.0.0/16 > 169.254.35.159  » [17:25:47] [mod.started] events.stream
169.254.0.0/16 > 169.254.35.159  » [17:25:47] [mod.started] net.recon

```

### Steps to Reproduce

1. Run `bettercap -iface "Wi-Fi"`

**Expected behavior:** *See all the traffic of my Wi-Fi*  

**Actual behavior:** *Error that it can' find matching "Wi-Fi".*

--

**Comment by zerocolTHS** [comment] 2019-02-03 17:20
You have not added your interface ie wlan0 or wlan0mon 
Check aircrack to see what your device is.

**Comment by bogiton** [comment] 2019-02-16 12:38
Try to use the MAC address of the interface as argument. It was first mentioned in issue #206

**Comment by evilsocket** [comment] 2019-03-09 11:01
duplicate of #206

**Closed by evilsocket** 2019-03-09 11:01 UTC
