### ISSUE TITLE
dns.spoof/arp.spoof

### ISSUE THREAD

**Issue by KERSED** [bettercap/bettercap#761] opened 2020-07-27 22:31 UTC
I'm having issues with getting dns spoofing to work. I am connected to my home network wirelessly on both a Raspberry Pi and my laptop, and setting the target as my laptop. I'm spoofing the dns to my RaspberryPi IP where I have a page running using an Apache server.

Here is what I'm doing:
>service apache2 start
>bettercap
>set arp.spoof.targets *my laptops IP*; arp.spoof on
>set dns.spoof.domains google.com; set dns.spoof.address *my RaspberryPi IP*; dns.spoof on

After entering those into the terminal I go on my laptop and attempt to access the spoofed domain and it continues to go to google.com. The screen on my Pi continues to show connection activity and will say it spoofed the dns. My expectations would be that it would for to my Raspberry Pi's IP where I have that index.html file. If I do type in my Raspberry Pi's ip into my laptops browser it access that page with no issues.

Any idea why this is happening? Is there a step that I am missing. Does it have to do with https with the spoofed domain?

Any help would be greatly appreciated!

Kali Linux on RaspberryPI B+
Bettercap Version 2.28

**Comment by phocean** [comment] 2020-09-04 12:49
Confirming that there are serious issues with ARP spoofing. Like no ARP requests sent at all even after starting the module.

Works flawlessly with legacy tools (ethercap, dsniff, bettercap 1.6), so definitely an issue with current versions.

**Comment by XiaoXiaoLui** [comment] 2020-09-10 18:04
I have same issue,  
Try to use nslookup to make dns request and use Wireshark to capture dns response packets, I found the reason for my issue:  the real dns response  comes before the fake dns response.   
But I don't know how to solved it.

**Comment by LouisBellinger** [comment] 2020-10-23 13:11
Got some issue with dns spoofing as well. Could not identify the root cause yet.

**Comment by leonobri** [comment] 2020-10-28 17:18
Same issue here, i thinks this is a current version issue.

**Comment by cgr71ii** [comment] 2020-12-01 06:39
I do not see that you had used `net.probe on` before `arp.spoof on`. I have not been using Bettercap too much, but in other issue I saw the one I think is the author saying that is needed to identify first the target before be able to use `arp.spoof on` or `dns.spoof on`. Before know that was not working for me neither, but now is working. Could you confirm? I checked out with tcpdump.

**Comment by aldo62** [comment] 2021-03-10 15:24
I've done all as described and still up to day, no succsess. Does not redirect https. Tried using ettercap (for arp poissoning)+activate from kernel ip_forward+iptables and use bettercap to read https. No succsess. Using bettercap alone kill the internet access in target. I find a little unstable as far as redirecting and spoofing in Bettercap.

**Comment by evilsocket** [comment] 2021-05-14 14:00
can't reproduce, all works on my side, and i don't see logs i can use to debug this, closing

**Comment by evilsocket** [comment] 2021-05-14 14:00
also no detail on the host OS, hardware, nothing ...

**Closed by evilsocket** 2021-05-14 14:00 UTC

**Comment by evilsocket** [comment] 2021-05-14 14:06
as expected, you can see the arp.spoof packets here, including the one at the end restoring the cache when i stopped the module ... guys you need to give me a bit more details to help debugging, like logs with -debug flag on, and more details about network card and operating system. Basically, use the github issue template that you ignored.

![98bf41d0-d5a3-41b6-9151-f469838f8a06](https://user-images.githubusercontent.com/86922/118282052-290e5580-b4ce-11eb-8402-b4275d944aee.png)
