### ISSUE TITLE
Improve net.recon verbosity options and events.stream documentation.

### ISSUE THREAD

**Issue by alexmozzhakov** [bettercap/bettercap#70] opened 2018-02-23 22:37 UTC
### Prerequisites

* [x] I read the [README](https://github.com/bettercap/bettercap/blob/master/README.md).
* [x] I am running the [latest source code version](https://github.com/bettercap/bettercap).
* [x] I already searched [other issues](https://github.com/bettercap/bettercap/issues?q=is%3Aopen+is%3Aissue+label%3Abug) to see if this problem was already reported.

### Description

There is no `net.recon` `verbosity` setting option,  but it could be very handy to filter net.recon  output data.
Also, IMHO, each module should have it.

**Comment by evilsocket** [comment] 2018-02-24 13:46
`net.recon` pushes events to the `events.stream`, if you don't want to see them, just `events.stream off` ... what verbosity are you referring to? Also, to clean up "output mess" (that output mess is called data btw), you can either use `events.stream clear` or just `clear` to clear the screen.

https://github.com/bettercap/bettercap/wiki/events.stream

**Comment by alexmozzhakov** [comment] 2018-02-24 14:23
I refer to `net.sniff.verbose` option. I would like to have the similar option for `net.recon`. I've checked code and understood that `net.recon` is highly related to net.sniff. What I called an output mess is endpoint detection and "losing". It's because I couldn't find target selection as for `--target` option of the previous version. That's why my output, targeting /22 network becomes messy.

**Comment by evilsocket** [comment] 2018-02-24 14:55
All modules are striclty related to the `events.stream`, basically each module triggers events and pushes them to this stream, than the `events.stream` module is responsible to print (or not) them, according to your  options, think about it as the global verbosity controller, so it's not a workaround at all if you use it. But yes, both documentation and `events.stream` options are sub optimal. I'll try to come up with something about that ;)

**Comment by evilsocket** [comment] 2018-02-24 16:09
Committed a more granular filter management and updated the wiki with a clearer explaination and a practical example of exactly what you're trying to do :)

**Closed by evilsocket** 2018-02-24 16:09 UTC
Labels: enhancement, new feature

**Comment by evilsocket** [comment] 2018-02-24 16:11
The problem is that I was not printing the event identifier I was mentioning in the documentation, now this has been fixed so users can see which events has which identifier and can suppress or enable them not only by module, but by tag `events.stream ignore endpoint.lost` or simply by prefix `events.stream ignore endpoint`.
