### ISSUE TITLE
Bettercap Seems to create various issues when using its pcap with hcxpcapngtool. 

### ISSUE THREAD

**Issue by Zetlin** [bettercap/bettercap#991] opened 2022-10-28 18:37 UTC
### Environment

Up to date Kali Linux X64 
Bettercap 2.32

Steps:

Sudo bettercap -iface wlan0
> wifi.recon on 
> set wifi.show.sort clients desc
> set ticker.commands 'clear; wifi.show'
> ticker on
Assoc or deauth a host 

Get the pcap 

 hcxpcapngtool -o test.pcap bettercap-wifi-handshakes.pcap 

Verbose output 

Information: limited dump file format detected!
This file format is a very basic format to save captured network data.
It is recommended to use PCAP Next Generation dump file format (or pcapng for short) instead.
The PCAP Next Generation dump file format is an attempt to overcome the limitations
of the currently widely used (but very limited) libpcap (cap, pcap) format.
https://www.wireshark.org/docs/wsug_html_chunked/AppFiles.html#ChAppFilesCaptureFilesSection
https://github.com/pcapng/pcapng

Warning: out of sequence timestamps!
This dump file contains frames with out of sequence timestamps.
That is a bug of the capturing tool.

Information: missing frames!
This dump file does not contain undirected proberequest frames.
An undirected proberequest may contain information about the PSK.
It always happens if the capture file was cleaned or
it could happen if filter options are used during capturing.
That makes it hard to recover the PSK.

Intended behavior: when dumping with hcxdumptool does not provide any of this additional information above.

**Comment by Zetlin** [comment] 2022-11-28 20:20
Any additional notes on this issue?

**Comment by sofakng** [comment] 2023-09-28 20:11
Also wondering about this ...

**Comment by evilsocket** [comment] 2024-08-16 15:09
duplicate of https://github.com/bettercap/bettercap/issues/939

**Closed by evilsocket** 2024-08-16 15:09 UTC
