### ISSUE TITLE
Device is shown multiple times with wrong mac address when arp.spoof is on and pc running bettercap lose connection

### ISSUE THREAD

**Issue by tonjo** [bettercap/bettercap#95] opened 2018-02-27 14:52 UTC
### Description
During arp spoofing, some endpoints are shown twice, with wrong mac address.
After stop spoofing, pc running bettercap is isolated from lan.

Full debug:
[betterbug.txt](https://github.com/bettercap/bettercap/files/1763316/betterbug.txt)

### Environment
* OS version: Ubuntu 16.04, kernel 4.13.0-36-generic
* bettercap version: from `go get ...` Tuesday 27 at 14:20 Italian time

### Steps to Reproduce
1. net.show
2. arp.spoof on
3. ping some device from pc running bettercap in net.show list
4. net.show (showing duplicate)
5. arp.spoof off
6. From shell: `ping <gateway>`: no answer 

**Expected behavior:**
Device already discovered should not appear again with another mac address.
PC should not lose connection after spoofing.

**Actual behavior:**
Old device with new mac address (pinging from pc running bettercap, it will have pc's mac address).
PC lose connection.

NOTE:
- **Full debug show an example with arp.spoof.targets set to one device, but is not necessary, 
issue is present even if spoofing entire lan**
- `ping` is just a way for generating traffic from pc to device, same thing happens when doing some activity from the device involving the pc (browse samba shares for example).
- After stop spoofing, arp cache of PC is intact:
    $ arp -an
    ? (192.168.1.1) at MAC_ADDRESS_GATEW [ether] on enp0s25
    ? (192.168.1.8) at MAC_ADDRESS_PHONE [ether] on enp0s25

**Comment by evilsocket** [comment] 2018-02-27 18:51
I'm trying this on an Ubuntu 17.10 with the same kernel, I can't reproduce the issue :S

**Comment by evilsocket** [comment] 2018-02-27 18:55
I tried a fix without being able to reproduce the issue, @tonjo please when you have time test if the fix worked :)

**Comment by evilsocket** [comment] 2018-02-27 18:59
@tonjo it'd be useful to know what router you have, how many interfaces on your pc ( `iface -a` ) and possibly the ARP table in the moment the bug happens ( `ip neigh` ).

**Comment by tonjo** [comment] 2018-02-27 21:54
Part of the bug is solved with last `go get`, no more duplicates,
but still as soon as I do `arp.spoof off` my pc is isolated.
But I think it's the router not restoring its own arp table.
Router is Vodafone Station Revolution (2nd version I think, [this one](http://lab.vodafone.it/forum/viewtopic.php?t=46999))

After arp.spoof my arp table (shown before with arp -an, now with ip neigh):
    
    192.168.1.1 dev enp0s25 lladdr MAC_ADDRESS_GATEW REACHABLE
    192.168.1.8 dev enp0s25 lladdr MAC_ADDRESS_PHONE STALE

I ran with WIRED network, I also have a wlan but is disabled by RF Kill switch.

    $ ifconfig -a   # *(isn't `iface` an entry in configuration files?)*
    enp0s25   Link encap:Ethernet  HWaddr MAC_ADDRESS_MYPC  
          inet addr:192.168.1.4  Bcast:192.168.1.255  Mask:255.255.255.0
          inet6 addr: IPV6 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:42936 errors:0 dropped:0 overruns:0 frame:0
          TX packets:28295 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:41504938 (41.5 MB)  TX bytes:3418162 (3.4 MB)
          Interrupt:20 Memory:d7500000-d7520000 

    lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:30194 errors:0 dropped:0 overruns:0 frame:0
          TX packets:30194 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:7117782 (7.1 MB)  TX bytes:7117782 (7.1 MB)

    wlo1      Link encap:Ethernet  HWaddr MAC_ADDRESS_WLAN  
          BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

Just for fun, I tried also a kali rolling on a different machine, wifi this time, and same problem, 
pc loses connection. Not fully tested though.

**Comment by evilsocket** [comment] 2018-02-28 00:55
Yeah it happens with some routers, if the arp table you see is correct after restoring than I can close this as fixed by the previous commit.

**Closed** 2018-02-28 00:56 UTC
Labels: can't reproduce
