### ISSUE TITLE
Device is shown multiple times with wrong mac address when arp.spoof is on

### ISSUE THREAD

**Issue by tonjo** [bettercap/bettercap#84] opened 2018-02-25 15:40 UTC
### Description
During arp spoofing, some endpoints are shown twice, with wrong mac address.

*Description of the bug or feature request*

### Environment
 * OS version: Ubuntu 16.04, kernel 4.13.0-36-generic
 * bettercap version: latest 

### Steps to Reproduce

1. net.show
2. arp.spoof on
3. **ping some device in net.show list**
4. net.show

**Expected behavior:** 
Device already discovered should not appear again with another mac address

**Actual behavior:** 
Old device with new mac address (pinging from pc running bettercap, it will have pc's mac address).

NOTE: 
Same thing happens when doing some activity from the device involving the pc
(browse samba shares for example).

**Comment by evilsocket** [comment] 2018-02-25 15:42
What is not clear about:

**Full debug output while reproducing the issue ( bettercap -debug ... ).** ?

**Comment by evilsocket** [comment] 2018-02-26 11:36
20 hours, not debug output provided. I'm closing this as I should have done since the very beginning.

**Closed by evilsocket** 2018-02-26 11:36 UTC
Labels: question
