### ISSUE TITLE
Bettercap v2.2 and 2.3 console hangs with both wifi.recon or net.probe (wlan* or eth*) - Kali2018.1

### ISSUE THREAD

**Issue by wcrigger** [bettercap/bettercap#198] opened 2018-03-21 23:17 UTC
Done

------

bettercap v2.2 and 2.3 become hung in both wifi.recon and net.probe modules without any additional interaction, only time.

### Environment

Please provide:

* Bettercap 2.3
* Kali2018.1
* go version go1.9.2 linux/amd64
* sudo ./bettercap -debug -iface wlan1
* No caplets needed, both just wifi.recon on wlan or net.probe on eth devices hang after a period of time.  In my debug session, I issued several commands as it seems more arbitrary commands speed this up.  However, just executing bettercap and only wifi.recon on or net.probe on will result in a hang after some time, usually when you come back to session and execute a command.  Full debug here:

[https://pastebin.com/xn0Ri2s0](https://pastebin.com/xn0Ri2s0)

1. Execute bettercap 2.2 or 2.3 with -iface wlan* or -iface eth*
2. Wait....
3. Execute a command

**Expected behavior:** *What you expected to happen*
Expected bettercap console not to hang

**Actual behavior:** *What actually happened*
Bettercap console hangs with or without much interactive activity, but activity seems to accelerate this and lessen the time that bettercap responds.
-- 

**♥ ANY INCOMPLETE REPORT WILL BE CLOSED RIGHT AWAY ♥**

**Comment by wcrigger** [comment] 2018-03-21 23:36
to be clear, this has been occurring usually when I start up bettercap in screen, detach, then resume it and issue either net.show or wifi.show.  In this example it hung on wifi.ap on..for which I'm not even sure is a valid command (exploring new features)..

**Comment by alexmozzhakov** [comment] 2018-03-22 07:13
@wcrigger `wifi.ap` is the command, but it doesn't really matter.

I've written about it in #190, but left an incomplete report, so it is closed.
```
Darwin Macbook.local 16.7.0 Darwin Kernel Version 16.7.0: root:xnu-3789.73.8~1/RELEASE_X86_64 x86_64
go version go1.10 darwin/amd64
```

**Comment by evilsocket** [comment] 2018-03-22 09:24
No debug output provided, report is incomplete, closing because i'm tired of explaining obvious stuff over and over again.

**Comment by evilsocket** [comment] 2018-03-22 09:39
lol i missed the debug log, reopening

**Comment by evilsocket** [comment] 2018-03-22 09:43
@wcrigger could you please confirm this happens systematically with `wifi.ap`? Also, while `wifi.ap` is running, are you able to type other commands? If so, does the output of `net.show` show increased sent bytes (thus `wifi.ap` is actually injecting packets)?

What if you don't use screen?

**Comment by wcrigger** [comment] 2018-03-22 10:54
hey so, this was the first time it hung on wifi.ap....ive had the issue with other commands such as just wifi.show with wifi.recon on and net.show with net.probe (and recon) on.  I'll run it outside of screen when I get to the office in debug, and will advise if this occurs without using screen.  Thanks!

**Comment by wcrigger** [comment] 2018-03-22 12:15
OK I reproduced the issue without screen.  Nothing was much different, except when hung (without screen), a CTRL+Z does background the hung process.  Needs a SIGTERM to terminate, AFAIK no way to recover.  Full debug on pastebin again =P

[https://pastebin.com/pmQ1UuLP](url)

Bettercap rocks btw!  I didn't start having this issue until sometime after 2.2 was released, and it has persisted into 2.3.

Thanks!

**Comment by wcrigger** [comment] 2018-03-22 12:17
As you will notice, this one hung on "events.show 20."  Seems like any command could cause it to hang under the right condition.  Not sure what that condition is, though.  I'm happy to help troubleshoot if you like.  Please note this has also occurred using -iface eth1 with just net.recon and net.probe enabled, after some time the console also becomes unresponsive without any fancy wifi stuff going on.

**Comment by evilsocket** [comment] 2018-03-22 12:27
Does it happen if you run only this https://github.com/bettercap/caplets/blob/master/netmon.cap ?

**Comment by wcrigger** [comment] 2018-03-22 12:34
Your questions surrounding wifi.ap.  I am doing another run *attempting* to address those questions....

It's up and running now with wifi.ap enabled with a random MAC of 06:fd:f7:c5:8f:76.  However, when I do a wifi.show, I do not see that BSSID.  If I attempt to wifi.recon 06:fd:f7:c5:8f:76, it states it cannot find that station.

I do have multiple wifi dongles, but in my limited testing, have not been able to run both in one session with -iface wlan0 -iface wlan1....when I attempted that, it seemed to use the last -iface argument.  Not sure multiple radios are supported.....Which is why often I use screen, one with each interface and go back and forth.

 Anyway, here's another debug with wifi.ap usage.  wifi.ap might be a red herring, since this also occurs without using a wlan...just ethernet with wifi.recon and net.probe on.

[https://pastebin.com/p4c1MZw1](url)

Thanks again.

**Comment by wcrigger** [comment] 2018-03-22 12:37
I'm running netmon.cap on ethernet interface and will let you know.

**Comment by evilsocket** [comment] 2018-03-22 12:38
Wait, let's not mix things, what `wifi.ap` produces is skipped by all `wifi.*` modules by default (it wouldn't make much sense showing it since you're the one creating it). 

Let's keep the test cases simple, i'm looking forward for `netmon.cap` outcome :)

**Comment by evilsocket** [comment] 2018-03-22 12:39
Basically I need to see what is the minimum / simplest set of modules we need to enable in order to reproduce this. If nothing happens with `netmon.cap` we know it's not a core issue but something related to `wifi.*` modules, otherwise it's deeper.

**Comment by wcrigger** [comment] 2018-03-22 13:10
Hasn't stopped responding yet with only netmon.cap (has been running ~30 minutes).  I'll leave that running to ensure it doesn't eventually occur with core.  I seem to recall however this occurring with net.recon and net.probe on, so either I'll  hit it again, or we may have to dig into other modules (net.sniff was also on as well the last time this occurred for me for similar scenario).

**Comment by evilsocket** [comment] 2018-03-22 13:24
If you can and when you have time, try to enable one module at a time, wait 20-30m and see if the session is stuck ... I'm doing it myself but can't reproduce the problem on my environment.

So I'd try to `net.sniff on` now (with the same parameters you were using before) and wait ...

**Comment by wcrigger** [comment] 2018-03-22 13:31
Still no sign of issue with just netmon.cap.  It would have been very difficult to capture the output with the ticker on, so I've executed it again with ticker on commented out.

However, in another instance, (and before I saw your latest response), I recreated the issue using the local-sniffer.cap configured as:

```
root@kali-desktop:~/go/bin# cat caplets/local-sniffer.cap
#events.stream off
events.clear
# set events.stream.filter net.sniff
# events.stream on

set net.sniff.verbose false
set net.sniff.local true
# https://biot.com/capstats/bpf.html
set net.sniff.filter not arp and not udp port 53

net.sniff on
```

In this case, it stopped responding fairly quickly.  This is the first I'm noticing the IPv6 messages.....debug output is here:

[https://pastebin.com/b3WVCQjr](url)

**Comment by wcrigger** [comment] 2018-03-22 13:52
OK, so I believe I have what you requested now.  I started bettercap in debug on eth0 with the netmon.cap, which did not crash.  However, after setting net.sniff.filter and net.sniff on, I see the captured packets until.....they simply stop appearing in the console.  Knowing something is wrong, I issue a couple more commands to attempt to trigger the bug (net.show, then net.sniff off finally killed it).

Full debug:

[https://pastebin.com/4PZnzVvb](url)

**Comment by evilsocket** [comment] 2018-03-22 14:38
Ooook, I think I know what's going on, give me a few minutes :D

**Comment by evilsocket** [comment] 2018-03-22 14:44
@wcrigger please can you confirm this commit fixed it in your setup as it did for mine?

**Closed** 2018-03-22 14:43 UTC
Labels: bug

**Comment by wcrigger** [comment] 2018-03-22 18:28
Thanks for the commit!  Sorry, got swamped @work there for a bit.....I'm updating and testing, will advise soon.

**Comment by wcrigger** [comment] 2018-03-22 18:59
No matter what I do, it's not becoming unresponsive......just as smooth and responsive as I've come to expect from bettercap.

Thanks again for the commit!  It seems to have worked like a charm.

**Comment by evilsocket** [comment] 2018-03-23 10:18
Yaaaayyyy -victory dance- :D thanks for reporting! D:
