### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by garlapann** [bettercap/bettercap#500] opened 2019-03-18 14:33 UTC
Hi, I just updated from master `go get github.com/bettercap/bettercap` and get the following output:

`bettercap v2.19 (built for android arm with go1.12.1) [type 'help' for a list of commands]`

`192.168.1.0/24 > 192.168.1.103  » panic: runtime error: invalid memory address or nil pointer dereference`
`[signal SIGSEGV: segmentation violation code=0x1 addr=0x4 pc=0xb66e92b0]`

`goroutine 7 [running]:`
`github.com/bettercap/bettercap/packets.(*Queue).TrackPacket(0x85c85d40, 0x55, 0x0)`
       `/data/data/com.termux/files/home/go/src/github.com/bettercap/bettercap/packets/queue.go:168 +0x34`
`github.com/bettercap/bettercap/packets.(*Queue).worker(0x85c85d40)`
       `/data/data/com.termux/files/home/go/src/github.com/bettercap/bettercap/packets/queue.go:202 +0xc8`
`created by github.com/bettercap/bettercap/packets.NewQueue`
        `/data/data/com.termux/files/home/go/src/github.com/bettercap/bettercap/packets/queue.go:80 +0x258`

### Environment

* Bettercap version you are using ( `bettercap -version` ).
  2.19 (compiled from master)
* OS version and architecture you are using.
  Android 6.0.1 arm, Termux 0.66
* Go version if building from sources.
  go1.12.1
* Command line arguments you are using.
  `export GOPATH=/data/data/com.termux/files/home/go`
  `export PKG_CONFIG=$PREFIX/bin/pkg-config`
  `go get github.com/bettercap/bettercap`
  `cd $GOPATH/bin && mv bettercap $PREFIX/bin && chmod 0700 $PREFIX/bin/bettercap`
  `sudo bettercap`

[strace.txt](https://github.com/bettercap/bettercap/files/2979601/strace.txt)

**Comment by garlapann** [comment] 2019-03-21 10:31
Can you deign to explain why you closed this issue? I still can't get _bettercap_ to work. If there is a problem with the latest _golang_ update, then I could not know that it would affect the compilation of your program... Several times I compiled _bettercap_ according to this scheme and everything worked. So what am I doing wrong, dear **Simone**?

**Comment by evilsocket** [comment] 2019-03-21 10:32
because i updated that part of the code and the issue should be fixed. Please pull the code, try and let me know if it's still there, in which case please provide an updated crash log and I'll reopen this issue.

**Comment by garlapann** [comment] 2019-03-21 10:36
Okay, I'm going to delete the $GOPATH directory and try again.

**Comment by garlapann** [comment] 2019-03-21 11:46
`$ echo $GOPATH`
`/data/data/com.termux/files/home/go`
`$ rm -rf ~/go ~/.cache`
`$ rm -f $PREFIX/bin/bettercap`
`$ export GOPATH=/data/data/com.termux/files/home/go`
`$ export PKG_CONFIG=$PREFIX/bin/pkg-config`
`$ go get **-u** github.com/bettercap/bettercap`
`$ ls -la $GOPATH/bin`
`total 26728`
`drwx------ 2 u0_a114 u0_a114         4096 Mar 21 14:29 .`
`drwx------ 4 u0_a114 u0_a114         4096 Mar 21 14:29 ..`
`-rwx------  1 u0_a114 u0_a114 27327272 **Mar 21 14:29** bettercap`
`$ cd $GOPATH/bin && mv bettercap $PREFIX/bin && chmod 0700 $PREFIX/bin/bettercap`
`$ sudo bettercap`
`bettercap v2.19 (built for android arm with go1.12.1) [type 'help' for a list of commands]`

`192.168.1.0/24 > 192.168.1.103  » panic: runtime error: invalid memory address or nil pointer dereference`
`[signal SIGSEGV: segmentation violation code=0x1 addr=0x4 pc=0xb66818a0]`

`goroutine 7 [running]:`
`github.com/bettercap/bettercap/packets.(*Queue).TrackPacket(0x85fa4000, 0x55, 0x0)`
       ` /data/data/com.termux/files/home/go/src/github.com/bettercap/bettercap/packets/queue.go:168 +0x34`
`github.com/bettercap/bettercap/packets.(*Queue).worker(0x85fa4000)`
        `/data/data/com.termux/files/home/go/src/github.com/bettercap/bettercap/packets/queue.go:202 +0xc8`
`created by github.com/bettercap/bettercap/packets.NewQueue`
        `/data/data/com.termux/files/home/go/src/github.com/bettercap/bettercap/packets/queue.go:80 +0x258`
`
$ sudo strace bettercap | cat > strace_new.txt`
[strace_new.txt](https://github.com/bettercap/bettercap/files/2991856/strace_new.txt)

**Comment by evilsocket** [comment] 2019-03-21 11:56
mmm this is super weird ... if you updated the code from master and recompiled, your [line 68 of queue.go](https://github.com/bettercap/bettercap/blob/master/packets/queue.go#L168) should only be an atomic increment operation, on a structure i know it can't be null ... i just pushed a check and a panic with a specific message if that happens anyway, could you be able to pull the new code and try again? thanks a ton!

**Comment by garlapann** [comment] 2019-03-21 11:58
trying again...

**Comment by evilsocket** [comment] 2019-03-21 11:59
thanks, and make sure the right binary ( `which bettercap` ) is actually being replaced :P

**Comment by garlapann** [comment] 2019-03-21 12:30
`$ echo $GOPATH`
`/data/data/com.termux/files/home/go`
`$ rm -rf ~/go ~/.cache`
`$ ls -la  ~/go ~/.cache`
`ls: cannot access '/data/data/com.termux/files/home/go': No such file or directory`
`ls: cannot access '/data/data/com.termux/files/home/.cache': No such file or directory`
`$ which bettercap`
`/data/data/com.termux/files/usr/bin/bettercap`
`$ rm -f /data/data/com.termux/files/usr/bin/bettercap`
`$ ls -la /data/data/com.termux/files/usr/bin/bettercap`
`ls: cannot access '/data/data/com.termux/files/usr/bin/bettercap': No such file or directory`
`$ go get -u github.com/bettercap/bettercap`
`$ ls -la $GOPATH/bin`
`total 26728`
`drwx------ 2 u0_a114 u0_a114         4096 Mar 21 15:16 .`
`drwx------ 4 u0_a114 u0_a114         4096 Mar 21 15:16 ..`
`-rwx------  1 u0_a114 u0_a114 27327312 Mar 21 15:16 bettercap`
`$ mv $GOPATH/bin/bettercap $PREFIX/bin && chmod 0700 $PREFIX/bin/bettercap`
`$ which bettercap`
`/data/data/com.termux/files/usr/bin/bettercap`
`$ ls -la /data/data/com.termux/files/usr/bin/bettercap`
`-rwx------ 1 u0_a114 u0_a114 27327312 Mar 21 15:16 /data/data/com.termux/files/usr/bin/bettercap`
`$ sudo bettercap`
`bettercap v2.19 (built for android arm with go1.12.1) [type 'help' for a list of commands]`

`192.168.1.0/24 > 192.168.1.103  » panic: runtime error: invalid memory address or nil pointer dereference`
`[signal SIGSEGV: segmentation violation code=0x1 addr=0x4 pc=0xb67098a8]`

`goroutine 7 [running]:`
`github.com/bettercap/bettercap/packets.(*Queue).TrackPacket(0x85f22120, 0x55, 0x0)`
        `/data/data/com.termux/files/home/go/src/github.com/bettercap/bettercap/packets/queue.go:173 +0x38`
`github.com/bettercap/bettercap/packets.(*Queue).worker(0x85f22120)`
        `/data/data/com.termux/files/home/go/src/github.com/bettercap/bettercap/packets/queue.go:207 +0xc8`
`created by github.com/bettercap/bettercap/packets.NewQueue`
        `/data/data/com.termux/files/home/go/src/github.com/bettercap/bettercap/packets/queue.go:81 +0x258`

$ sudo strace bettercap | cat > strace_newest.txt
[strace_newest.txt](https://github.com/bettercap/bettercap/files/2992005/strace_newest.txt)

**Comment by evilsocket** [comment] 2019-03-21 12:32
mmm it seems related to https://github.com/golang/go/issues/23345 ... which according to your go version should be free from that bug already ...

**Comment by evilsocket** [comment] 2019-03-21 12:34
another potential fix (sorry for the pain in the ass but i can't reproduce it locally :/), need pull and test again

**Closed** 2019-03-21 12:34 UTC

**Comment by garlapann** [comment] 2019-03-21 12:36
write when I can try again

**Comment by evilsocket** [comment] 2019-03-21 12:37
now

**Comment by garlapann** [comment] 2019-03-21 12:38
ок, starting)))

**Comment by garlapann** [comment] 2019-03-21 13:06
**You are a genius! The program started! Not tested yet, but the launch looks fine!**

`$ rm -rf ~/go ~/.cache`
`$ ls -la ~/go ~/.cache`
`ls: cannot access '/data/data/com.termux/files/home/go': No such file or directory`
`ls: cannot access '/data/data/com.termux/files/home/.cache': No such file or directory`
`$ which bettercap`
`/data/data/com.termux/files/usr/bin/bettercap`
`$ rm -f /data/data/com.termux/files/usr/bin/bettercap`
`$ ls -la /data/data/com.termux/files/usr/bin/bettercap`
`ls: cannot access '/data/data/com.termux/files/usr/bin/bettercap': No such file or directory`
`$ go get -u github.com/bettercap/bettercap`
`$ ls -la ~/go/bin`
`total 26728`
`drwx------ 2 u0_a114 u0_a114     4096 Mar 21 15:53 .`
`drwx------ 4 u0_a114 u0_a114     4096 Mar 21 15:53 ..`
`-rwx------ 1 u0_a114 u0_a114 27327316 Mar 21 15:53 bettercap`
`$ mv ~/go/bin/bettercap $PREFIX/bin && chmod 0700 $PREFIX/bin/bettercap`
`$ which bettercap`
`/data/data/com.termux/files/usr/bin/bettercap`
`$ ls -la /data/data/com.termux/files/usr/bin/bettercap`
`-rwx------ 1 u0_a114 u0_a114 27327316 Mar 21 15:53 /data/data/com.termux/files/usr/bin/bettercap`
`$ sudo bettercap`
`bettercap v2.19 (built for android arm with go1.12.1) [type 'help' for a list of commands]`

`192.168.1.0/24 > 192.168.1.103  » [12:58:00] [endpoint.new] endpoint 192.168.1.100 detected as 20:cf:30:7e:dc:fc (ASUSTek COMPUTER INC.).`
`192.168.1.0/24 > 192.168.1.103  » [12:58:00] [endpoint.new] endpoint 192.168.1.106 detected as 50:8f:4c:fb:0c:aa (Xiaomi Communications Co Ltd).`
`192.168.1.0/24 > 192.168.1.103  » q`

**Comment by evilsocket** [comment] 2019-03-21 13:07
*blind bug fixing ftw!!!* XD thanks for your report, help and patience! :D

**Comment by garlapann** [comment] 2019-03-21 13:08
Thank you for your brains!
