### ISSUE TITLE
OS X  2.17  Error

### ISSUE THREAD

**Issue by Gavin7E** [bettercap/bettercap#462] opened 2019-02-25 15:01 UTC
192.168.0.0/24 > 192.168.0.159  » wifi.recon on
ERROR for 'iw [reg set BO]': exec: "iw": executable file not found in $PATH
[22:59:15] [sys.log] [err] exec: "iw": executable file not found in $PATH

192.168.0.0/24 > 192.168.0.159  » http.proxy on
[23:00:35] [sys.log] [inf] http.proxy enabling forwarding.
[23:00:35] [sys.log] [err] exit status 1

OS X Mojave 10.14.3

**Comment by evilsocket** [comment] 2019-02-25 16:36
duplicate of https://github.com/bettercap/bettercap/issues/454

**Closed by evilsocket** 2019-02-25 16:36 UTC
