### ISSUE TITLE
Seeing duplicate gateway with a random IP and hostname that keeps changing and also random devices

### ISSUE THREAD

**Issue by Neal** [bettercap/bettercap#82] opened 2018-02-25 04:05 UTC
### Description

`net.show` is showing the gateway twice with the second time with a random IP address and hostname (eg. IP owned by Twitter or Google or AWS). It also shows two IPv4 Multicast devices that did not used to show up until yesterday.

### Environment

* macOS High Sierra 10.13.3 Beta (17D25b)
* go version go1.9.4 darwin/amd64
* `bettercap --debug`

<details><summary>Full debug output</summary><p>

```
bettercap v2.0.0RC2 (type 'help' for a list of commands)

[19:33:35] [sys.log] [dbg] env.change: ticker.commands -> 'clear; net.show'
[19:33:35] [sys.log] [dbg] env.change: ticker.period -> '1'
❯ [19:33:35] [sys.log] [dbg] env.change: mac.changer.iface -> '<interface name>'
❯ [19:33:35] [sys.log] [dbg] env.change: mac.changer.address -> '<random mac>'
❯ [19:33:35] [sys.log] [dbg] env.change: net.probe.throttle -> '10'
❯ [19:33:35] [sys.log] [dbg] env.change: arp.spoof.targets -> '<entire subnet>'
❯ [19:33:35] [sys.log] [dbg] env.change: dhcp6.spoof.domains -> 'microsoft.com, goole.com, facebook.com, apple.com, twitter.com'
❯ [19:33:35] [sys.log] [dbg] env.change: dns.spoof.domains -> '*'
❯ [19:33:35] [sys.log] [dbg] env.change: dns.spoof.address -> '<interface address>'
❯ [19:33:35] [sys.log] [dbg] env.change: dns.spoof.all -> 'false'
❯ [19:33:35] [sys.log] [dbg] env.change: net.sniff.verbose -> 'true'
❯ [19:33:35] [sys.log] [dbg] env.change: net.sniff.local -> 'false'
❯ [19:33:35] [sys.log] [dbg] env.change: net.sniff.filter -> 'not arp'
❯ [19:33:35] [sys.log] [dbg] env.change: net.sniff.regexp -> ''
❯ [19:33:35] [sys.log] [dbg] env.change: net.sniff.output -> ''
❯ [19:33:35] [sys.log] [dbg] env.change: net.sniff.source -> ''
❯ [19:33:35] [sys.log] [dbg] env.change: http.server.path -> '.'
❯ [19:33:35] [sys.log] [dbg] env.change: http.server.address -> '<interface address>'
❯ [19:33:35] [sys.log] [dbg] env.change: http.server.port -> '80'
❯ [19:33:35] [sys.log] [dbg] env.change: http.server.certificate -> ''
❯ [19:33:35] [sys.log] [dbg] env.change: http.server.key -> ''
❯ [19:33:35] [sys.log] [dbg] env.change: http.port -> '80'
❯ [19:33:35] [sys.log] [dbg] env.change: http.proxy.address -> '<interface address>'
❯ [19:33:35] [sys.log] [dbg] env.change: http.proxy.port -> '8080'
❯ [19:33:35] [sys.log] [dbg] env.change: http.proxy.script -> ''
❯ [19:33:35] [sys.log] [dbg] env.change: https.port -> '443'
❯ [19:33:35] [sys.log] [dbg] env.change: https.proxy.address -> '<interface address>'
❯ [19:33:35] [sys.log] [dbg] env.change: https.proxy.port -> '8083'
❯ [19:33:35] [sys.log] [dbg] env.change: https.proxy.certificate -> '~/.bettercap-ca.cert.pem'
❯ [19:33:35] [sys.log] [dbg] env.change: https.proxy.key -> '~/.bettercap-ca.key.pem'
❯ [19:33:35] [sys.log] [dbg] env.change: https.proxy.script -> ''
❯ [19:33:35] [sys.log] [dbg] env.change: tcp.port -> '443'
❯ [19:33:35] [sys.log] [dbg] env.change: tcp.address -> ''
❯ [19:33:35] [sys.log] [dbg] env.change: tcp.proxy.address -> '<interface address>'
❯ [19:33:35] [sys.log] [dbg] env.change: tcp.proxy.port -> '8443'
❯ [19:33:35] [sys.log] [dbg] env.change: tcp.proxy.script -> ''
❯ [19:33:35] [sys.log] [dbg] env.change: api.rest.address -> '<interface address>'
❯ [19:33:35] [sys.log] [dbg] env.change: api.rest.port -> '8083'
❯ [19:33:35] [sys.log] [dbg] env.change: api.rest.username -> ''
❯ [19:33:35] [sys.log] [dbg] env.change: api.rest.password -> ''
❯ [19:33:35] [sys.log] [dbg] env.change: api.rest.certificate -> '~/.bcap-api.rest.certificate.pem'
❯ [19:33:35] [sys.log] [dbg] env.change: api.rest.key -> '~/.bcap-api.rest.key.pem'
❯ [19:33:35] [sys.log] [dbg] env.change: wifi.recon.channel -> ''
❯ [19:33:35] [sys.log] [dbg] env.change: wifi.hop.period -> '250'
❯ [19:33:35] [sys.log] [dbg] env.change: wifi.skip-broken -> 'true'
❯ [19:33:35] [sys.log] [dbg] env.change: iface.index -> '8'
❯ [19:33:35] [sys.log] [dbg] env.change: iface.name -> 'en0'
❯ [19:33:35] [sys.log] [dbg] env.change: iface.ipv4 -> '192.168.0.29'
❯ [19:33:35] [sys.log] [dbg] env.change: iface.ipv6 -> 'fd00:bc4d:fb98:1c32:f4bd:c0f2:b8b:b906'
❯ [19:33:35] [sys.log] [dbg] env.change: iface.mac -> 'dc:a9:04:xx:xx:xx'
❯ [19:33:35] [sys.log] [dbg] env.change: gateway.address -> '192.168.0.1'
❯ [19:33:35] [sys.log] [dbg] env.change: gateway.mac -> 'bc:4d:fb:98:1c:32'
❯ [19:33:35] [sys.log] [dbg] env.change: log.debug -> 'true'
❯ [19:33:35] [sys.log] [dbg] env.change: log.silent -> 'false'
❯ [19:33:35] [session.started] {session.started 2018-02-24 19:33:35.509364 -0800 PST m=+0.077244043 <nil>}
❯ [19:33:35] [mod.started] events.stream
❯ [19:33:35] [mod.started] net.recon
❯ [19:33:35] [endpoint.new] Endpoint 192.168.0.24 (appletv) detected as 40:cb:c0:xx:xx:xx.
❯ [19:33:35] [endpoint.new] Endpoint 224.0.0.251 detected as 01:00:5e:00:00:fb.
❯ [19:33:35] [endpoint.new] Endpoint 239.255.255.250 detected as 01:00:5e:7f:ff:fa.
❯ [19:33:38] [endpoint.new] Endpoint 199.59.148.241 detected as bc:4d:fb:98:1c:32 (Hitron Technologies.).
❯ net.show

+-----------------+-------------------+-----------------------------+-----------------------------+--------+--------+-----------+
|       IP        |        MAC        |            NAME             |           VENDOR            |  SENT  | RECVD  | LAST SEEN |
+-----------------+-------------------+-----------------------------+-----------------------------+--------+--------+-----------+
| 192.168.0.29    | dc:a9:04:xx:xx:xx | en0                         | Apple                       | 17 kB  | 17 kB  | 19:33:35  |
| 192.168.0.1     | bc:4d:fb:98:1c:32 | gateway                     | Hitron Technologies.        | 28 kB  | 1.3 kB | 19:33:35  |
|                 |                   |                             |                             |        |        |           |
| 192.168.0.24    | 40:cb:c0:xx:xx:xx | appletv                     |                             | 0 B    | 0 B    | 19:33:35  |
| 199.59.148.241  | bc:4d:fb:98:1c:32 | r-199-59-148-241.twttr.com. | Hitron Technologies.        | 1.1 kB | 660 B  | 19:33:52  |
| 224.0.0.251     | 01:00:5e:00:00:fb |                             |                             | 0 B    | 0 B    | 19:33:35  |
| 239.255.255.250 | 01:00:5e:7f:ff:fa |                             |                             | 0 B    | 25 kB  | 19:33:35  |
+-----------------+-------------------+-----------------------------+-----------------------------+--------+--------+-----------+

❯ [19:47:19] [endpoint.lost] Endpoint 199.59.148.241 (r-199-59-148-241.twttr.com.) lost.
❯ [19:47:20] [endpoint.new] Endpoint 54.190.15.71 detected as bc:4d:fb:98:1c:32 (Hitron Technologies.).
❯ [19:47:41] [endpoint.lost] Endpoint 54.190.15.71 (ec2-54-190-15-71.us-west-2.compute.amazonaws.com.) lost.
❯ [19:47:41] [endpoint.new] Endpoint 199.59.148.241 detected as bc:4d:fb:98:1c:32 (Hitron Technologies.).
```

</p></details>

---
**Expected behavior:**

- Should not see the `Hitron Technologies` gateway twice.
- Should not see a Twitter IP address and hostname for the gateway.
- Possibly shouldn't see the last two devices (vendor is IPv4 Multicast - not sure where they are from)

**Actual behavior:**

- Seeing the `Hitron Technologies` gateway twice.
- Duplicated gateway shows IP address owned by Twitter and a twttr.com hostname (note: this changes to any other random IP and hostname each time I run bettercap). Every few minutes it "loses" this device and then finds it again with another IP address.
- Seeing two IPv4 Multicast devices(?)

**Comment by evilsocket** [comment] 2018-02-25 04:06
is it possible to have a screenshot?

**Comment by tonjo** [comment] 2018-02-25 11:57
I see something similar, and also duplicated devices (not gateway) with **my pc mac address**!
Example (cutting some columns), `smartphone1` is an alias for `MAC_ADDRESS_PHONE`

       +--------------+-------------------+----------------------+
       |      IP      |        MAC        |         NAME         |   
       +--------------+-------------------+----------------------+
        | 192.168.1.8  | MAC_ADDRESS_PHONE | smartphone1
        | 192.168.1.8  | MAC_ADDRESS_MY_PC | HUAWEI_nova.station.

And when I stop arp.spoof, my pc can not connect to internet, even if it's arp cache is good, not even pinging the gateway.
I decided to write here instead of filling another issue because is quite similar, but if needed I will fill another one.

**Comment by alexmozzhakov** [comment] 2018-02-25 12:28
I also saw 8.8.8.8 which is set up as my DNS

**Comment by evilsocket** [comment] 2018-02-25 12:42
There was a bug in the way the subnet bits were initialized, so whenever I checked `if isThisIpInMyNetwork(new_ip)` that returned true. It should be fixed now, @alexmozzhakov can you pull and give it a try? I can't fully reproduce it on my network.

**Comment by tonjo** [comment] 2018-02-25 13:26
# bettercap
bettercap v2.0.0RC2 (type 'help' for a list of commands)

		0.0.0.0/64 > 192.168.1.4  » panic: runtime error: invalid memory address or nil pointer dereference
		[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x520546]

		goroutine 40 [running]:
		net.networkNumberAndMask(0x0, 0xc420414c70, 0x5215be, 0xc42007a00a, 0x2, 0xc4200180c0, 0x10)
			/usr/lib/go-1.9/src/net/ip.go:445 +0x26
		net.(*IPNet).Contains(0x0, 0xc4200180c0, 0x10, 0x10, 0x10)
			/usr/lib/go-1.9/src/net/ip.go:469 +0x2f
		github.com/bettercap/bettercap/network.(*LAN).shouldIgnore(0xc42036ec30, 0xc42007a000, 0xc, 0xc420014240, 0x11, 0x0)
			/home/tonjo/prj/go/src/github.com/bettercap/bettercap/network/lan.go:145 +0x10f
		github.com/bettercap/bettercap/network.(*LAN).AddIfNew(0xc42036ec30, 0xc42007a000, 0xc, 0xc420014240, 0x11, 0x0)
			/home/tonjo/prj/go/src/github.com/bettercap/bettercap/network/lan.go:189 +0xcb
		github.com/bettercap/bettercap/modules.(*Discovery).runDiff(0xc42007da40, 0xc420076450)
			/home/tonjo/prj/go/src/github.com/bettercap/bettercap/modules/net_recon.go:87 +0x228
		github.com/bettercap/bettercap/modules.(*Discovery).Start.func1()
			/home/tonjo/prj/go/src/github.com/bettercap/bettercap/modules/net_recon.go:108 +0x10f
		created by github.com/bettercap/bettercap/session.(*SessionModule).SetRunning
			/home/tonjo/prj/go/src/github.com/bettercap/bettercap/session/module.go:150 +0x1a0

**Comment by evilsocket** [comment] 2018-02-25 13:28
@tonjo yes I'm sorry there was a bad bug, pull now and it should be gone :)

**Comment by alexmozzhakov** [comment] 2018-02-25 13:32
@evilsocket sure. DNS no longer appears. The other thing occurs (same MAC) [screenshot](https://ibb.co/dzHYnc)

**Comment by evilsocket** [comment] 2018-02-25 13:36
@alexmozzhakov thank you so much! may i also have your `sudo netstat -an` output from that machine please?

**Comment by tonjo** [comment] 2018-02-25 13:37
Yep, duplicated issue still there, and again my pc connection is lost when stop spoofing.
PS: Finally I got to try this, it's amazing.

**Comment by alexmozzhakov** [comment] 2018-02-25 13:41
@evilsocket Sorry, do you want something specific?

**Comment by evilsocket** [comment] 2018-02-25 13:41
@alexmozzhakov feel free to delete the last bytes of the macs and ips, I need to see if the problem is in the way the arp cache is parsed or somewhere else.

**Comment by alexmozzhakov** [comment] 2018-02-25 13:48
https://pastebin.com/Az3MGtSX

**Comment by evilsocket** [comment] 2018-02-25 13:51
@alexmozzhakov OMG I'm sorry, I meant `sudo arp -an` ... working on too many things at the same time i guess XD

**Comment by tonjo** [comment] 2018-02-25 13:54
If it is useful, my `arp -an` is correct, like this, but still NOT pinging gateway. Magic?

		$ arp -an
		? (192.168.1.8) at MAC_ADDRESS_PHONE [ether] on enp0s25
		? (192.168.1.1) at MAC_ADDRESS_GATEW [ether] on enp0s25

**Comment by evilsocket** [comment] 2018-02-25 13:57
@tonjo if i'm asking something to @alexmozzhakov, you adding your own netstat and talking about a different bug does not help, please stop. I'm trying to fix a bug at a time here.

**Comment by alexmozzhakov** [comment] 2018-02-25 13:57
@evilsocket haha, ok. Keep calm. My `arp` is going crazy after running bettercap.  The output looks like: 
```
? (10.114.71.235) at (incomplete) on en1 ifscope [ethernet]
? (10.114.71.236) at (incomplete) on en1 ifscope [ethernet]
? (10.114.71.237) at (incomplete) on en1 ifscope [ethernet]
? (10.114.71.238) at (incomplete) on en1 ifscope [ethernet]
? (10.114.71.239) at (incomplete) on en1 ifscope [ethernet]
? (10.114.71.240) at (incomplete) on en1 ifscope [ethernet]
```

**Comment by evilsocket** [comment] 2018-02-25 13:58
I only need the records with a mac address ... there's something very wrong about that arp btw O.o

**Comment by alexmozzhakov** [comment] 2018-02-25 14:01
@evilsocket it will only have MAC instead of incomplete  (incomplete). I'm not sure if it's bettercap issue at all.

**Comment by evilsocket** [comment] 2018-02-25 14:05
yes but what macs to what ips? do you see the duplicates there?

**Comment by tonjo** [comment] 2018-02-25 14:12
Sorry, didn't mean to mess, and speaking of the same bug, in my case I see duplicated line in bettercap but arp is still good (no duplicates).

**Comment by alexmozzhakov** [comment] 2018-02-25 14:25
@evilsocket I'm so sorry. There weren't duplicates. They had a different char I haven't noticed. Should've rechecked it twice. Sorry for the inconvenience.

**Comment by evilsocket** [comment] 2018-02-25 14:28
AHAHHAHAHAHAHHA good thing you noticed now, I was becoming crazy XD so, how is it going now? :D (no worries dude, you're helping me a lot ;) )

**Comment by tonjo** [comment] 2018-02-25 14:32
I still have duplicates. Two lines, one with right mac address, the other with same ip but **my pc's mac address**. Event show a "new device" with same ip but wrong mac address.

**Comment by evilsocket** [comment] 2018-02-25 14:34
@tonjo please provide required details as specified in the ISSUE_TEMPLATE file if you want support.

**Comment by alexmozzhakov** [comment] 2018-02-25 14:36
I don't have any duplicates nor other bugs so far, except #80, so I will try to investigate it further.

**Comment by evilsocket** [comment] 2018-02-25 15:01
@tonjo did you pull the latest code version and recompiled before trying again? May I have your debug output, a screenshot, something?

**Comment by evilsocket** [comment] 2018-02-25 15:16
Bug fixed, @tonjo is simply using the precompiled version and for some reasons he expects my fixes to magically propagate there without updating.

**Closed by evilsocket** 2018-02-25 15:16 UTC
Labels: bug, osx
