### ISSUE TITLE
Exit status 234 bettercap

### ISSUE THREAD

**Issue by Decapitater** [bettercap/bettercap#906] opened 2021-08-08 12:02 UTC
### Environment

Please provide:

* version=v2.31.1
*kali arm64.
* Sudo Bettercap 
* wifi.recon on
* **Full debug output** while reproducing the issue ( `bettercap -debug ...` ).
WARNING: wifi error while activating handle error Wlan1 SIOCGIWPRIV
Argument list is too long interface might already be in monitor mode
WARNING wifi error while hopping to Channel 14 iw:out=kernel reports:Channel is disabled command failed Invalid argument (-22) err=exit status234
WARNING wifi error while hopping to Channel 13 iw:out=kernel reports:Channel is disabled command failed Invalid argument (-22) err=exit status234
WARNING wifi error while hopping to Channel 12 iw:out=kernel reports:Channel is disabled command failed Invalid argument (-22) err=exit status234
### Steps to Reproduce

1. type "sudo bettercap"
2. type "wifi.recon on"
3. tada !

**Expected behavior:** bettercap will search wifi and show them on screen 

**Actual behavior:** the error showed and no wifi is searched 

-- 
EXTRAS:
Bettercap wasn't working with normal pcap due to bug so i changed it to libpcap 1.9.1-4.
In the past i worked like charm and still continue to do so today.
the internal wifi scan is also non functional rtl8188eus with compatible drivers , rtl8188au , rtl8xx , etc are all showing the same result 
**♥ ANY INCOMPLETE REPORT WILL BE CLOSED RIGHT AWAY ♥**

**Comment by Decapitater** [comment] 2021-08-08 13:43
@evilsocket  it would be great if you can help as a similar post 
issue:881 has provided no good insights to problem

**Comment by evilsocket** [comment] 2021-08-09 08:48
duplicate of #881

**Closed by evilsocket** 2021-08-09 08:48 UTC

**Comment by Decapitater** [comment] 2021-08-09 09:43
issue:881 has provided no good insights to problem
@evilsocket there is usefull info
