### ISSUE TITLE
index out of range errors (packets/dot11.go)

### ISSUE THREAD

**Issue by yungtravla** [bettercap/bettercap#167] opened 2018-03-11 09:34 UTC
### Prerequisites

:+1: 

### Description

Several 'index out of range' errors occur in packets/dot11.go
This particular one happened on line 237, but I've had it happen on line 151 as well.

### Environment

Please provide:

* Bettercap version you are using.
`v2.1`
* OS version and architecture you are using.
`Linux ghxst 4.14.0-kali3-amd64 #1 SMP Debian 4.14.17-1kali1 (2018-02-16) x86_64 GNU/Linux`
* Go version if building from sources.
`go version go1.10rc2 linux/amd64`
* Command line arguments you are using.
`sudo bettercap`
* Caplet code you are using (if any).
`Not using any`
* Interactive session commands you are using (if any).
`wifi.recon on`
* **Full debug output** while reproducing the issue ( `bettercap -debug ...` ).

```
[18:48:25] [sys.log] [inf] WiFi recon active with channel hopping.
[18:48:25] [mod.started] wifi.recon
192.168.1.0/24 > 192.168.1.12  » [18:48:25] [sys.log] [inf] Channel hopper started.
192.168.1.0/24 > 192.168.1.12  » [18:48:25] [sys.log] [dbg] WiFi stations pruner started.
192.168.1.0/24 > 192.168.1.12  » [18:48:25] [wifi.ap.new] WiFi access point XXXXXXXXXX (-53 dBm) detected as xx:xx:xx:xx:xx:xx (Netgear).
192.168.1.0/24 > 192.168.1.12  » [18:48:25] [wifi.ap.new] WiFi access point XXXXXXXXX (-49 dBm) detected as xx:xx:xx:xx:xx:xx (Huawei Technologies Co.).
192.168.1.0/24 > 192.168.1.12  » [18:48:27] [wifi.ap.new] WiFi access point XXXXXXXXXXX (-75 dBm) detected as xx:xx:xx:xx:xx:xx.
192.168.1.0/24 > 192.168.1.12  » [18:48:34] [endpoint.lost] Endpoint 192.168.1.4 (Google) lost.
192.168.1.0/24 > 192.168.1.12  » [18:48:34] [endpoint.lost] Endpoint 192.168.1.10 lost.
192.168.1.0/24 > 192.168.1.12  » [18:48:45] [wifi.ap.new] WiFi access point �:XXXXXXXXX (-73 dBm) detected as xx:xx:xx:xx:xx:xx.
192.168.1.0/24 > 192.168.1.12  » [18:48:49] [wifi.ap.new] WiFi access point XXXXXXXXX-5G (-55 dBm) detected as xx:xx:xx:xx:xx:xx (Huawei Technologies Co.).
192.168.1.0/24 > 192.168.1.12  » [18:49:37] [wifi.ap.new] WiFi access point Xǥa��XX (-72 dBm) detected as xx:xx:xx:xx:xx:xx (Netgear).
192.168.1.0/24 > 192.168.1.12  » panic: runtime error: index out of range

goroutine 127 [running]:
github.com/bettercap/bettercap/packets.Dot11ParseEncryption(0xbe7fe0, 0xc420640140, 0xc4204dc0a0, 0xc42067a000, 0x0, 0x0, 0x0, 0x8000101, 0x0, 0xffffffffffffffff)
	/root/go/src/github.com/bettercap/bettercap/packets/dot11.go:237 +0x898
github.com/bettercap/bettercap/modules.(*WiFiRecon).updateStats(0xc4200ece70, 0xc4204dc0a0, 0xbe7fe0, 0xc420640140)
	/root/go/src/github.com/bettercap/bettercap/modules/wifi_recon.go:524 +0x6a
github.com/bettercap/bettercap/modules.(*WiFiRecon).Start.func1()
	/root/go/src/github.com/bettercap/bettercap/modules/wifi_recon.go:637 +0x307
created by github.com/bettercap/bettercap/session.(*SessionModule).SetRunning
	/root/go/src/github.com/bettercap/bettercap/session/module.go:150 +0x1a0

```

### Steps to Reproduce

`sudo bettercap`

In the interactive session:

`wifi.recon on`

**Actual behavior:** *What actually happened*

As you can see in the event stream, some network ESSIDs show weird unicode characters. After about 20 seconds it throws the 'index out of range' error (at line 237 and sometimes at line 151 in packets/dot11.go)

I read [here](https://github.com/bettercap/bettercap/issues/80) that support for dot11 isn't up to scratch yet.

I think this might have to do with improper parsing of dot11 frames from 5GHz networks in my area, not sure though.

Hope this helps :v:

**Comment by evilsocket** [comment] 2018-03-11 12:51
Mmmm what's the value of your `wifi.skip-broken` ?

**Comment by evilsocket** [comment] 2018-03-11 13:42
Also a `.pcap` from your monitor interface while this happens would be great to reproduce it :)

**Comment by yungtravla** [comment] 2018-03-11 13:43
I didn't change it so I assume the default value true

**Comment by yungtravla** [comment] 2018-03-11 13:44
Ok, I'll upload a pcap in the morning :)

**Comment by evilsocket** [comment] 2018-03-11 14:37
It should be fixed, but I can't reproduce it so not 100% sure, as soon as you can confirm (or not) please let us know :)

**Closed** 2018-03-11 14:36 UTC
Labels: bug, can't reproduce

**Comment by yungtravla** [comment] 2018-03-11 14:40
Cool :) I'll update now and check tomorrow :+1:

**Comment by yungtravla** [comment] 2018-03-11 17:34
Can't sleep, must bettercap... ;)

It no longer panics, but I'm still getting some unicode symbols:


```
192.168.1.0/24 > 192.168.1.19  » wifi.show

+----------+--------------------+---------------------+-------------------+----------+----------+---------+--------+------------+
|  RSSI    |       BSSID        |        SSID         |    Encryption     | Channel  | Clients  |  Sent   | Recvd  | Last Seen  |
+----------+--------------------+---------------------+-------------------+----------+----------+---------+--------+------------+
| -55 dBm  | xx:xx:xx:xx:xx:xx  | XmEX-%JXf           | OPEN              | 1        |          |         |        | 01:58:52   |
| -60 dBm  | xx:xx:xx:xx:xx:xx  | XXXXXXXXX-5G        | WPA2 (CCMP, PSK)  | 36       | 7        | 21 kB   | 11 kB  | 02:00:54   |
| -61 dBm  | xx:xx:xx:xx:xx:xx  | XXXXXXXXXXXXXXXXX   | OPEN              | 5        |          |         |        | 02:00:51   |
| -63 dBm  | xx:xx:xx:xx:xx:xx  | XXXXXXXXXXX         | WPA2 (CCMP, PSK)  | 1        |          | 1.7 kB  |        | 02:00:48   |
| -67 dBm  | xx:xx:xx:xx:xx:xx  | XXXXXXXXXXXX        | WPA2 (CCMP, PSK)  | 10       |          |         |        | 01:57:47   |
| -73 dBm  | xx:xx:xx:xx:xx:xx  | XXXXXXXXX           | WPA2 (CCMP, PSK)  | 2        |          | 13 kB   |        | 02:00:52   |
| -75 dBm  | xx:xx:xx:xx:xx:xx  | XXXXXXXXXXX         | WPA2 (CCMP, PSK)  | 11       |          |         |        | 01:58:05   |
+----------+--------------------+---------------------+-------------------+----------+----------+---------+--------+------------+
192.168.1.0/24 > 192.168.1.19  » [02:03:52] [wifi.ap.lost] WiFi access point XmEX-%JXf (xx:xx:xx:xx:xx:xx) lost.
192.168.1.0/24 > 192.168.1.19  » [02:04:39] [wifi.ap.new] WiFi access point � (-72 dBm) detected as xx:xx:xx:xx:xx:xx (Huawei Technologies Co.).
192.168.1.0/24 > 192.168.1.19  » [02:04:54] [wifi.ap.new] WiFi access point XXXXXXXXX (-55 dBm) detected as xx:xx:xx:xx:xx:xx.
192.168.1.0/24 > 192.168.1.19  » [02:04:56] [wifi.ap.new] WiFi access point �tn (-74 dBm) detected as xx:xx:xx:xx:xx:xx.
192.168.1.0/24 > 192.168.1.19  » [02:04:58] [wifi.ap.lost] WiFi access point � (xx:xx:xx:xx:xx:xx) lost.
```

**Comment by evilsocket** [comment] 2018-03-12 12:04
In order to understand that, we need a pcap.
