### ISSUE TITLE
Missing MacOS Release

### ISSUE THREAD

**Issue by SubZero5** [bettercap/bettercap#865] opened 2021-04-17 16:38 UTC
To: @caquino and @evilsocket,

Release **v2.31.0** still does not have its darwin release **bettercap_darwin_amd64_v2.31.0.zip**

Ref: #846 is not fixed (I guess).

**Comment by evilsocket** [comment] 2021-04-17 16:43
yep i've noticed, the build just gets stuck for reasons unknown :/

**Comment by evilsocket** [comment] 2021-04-17 16:44
https://travis-ci.org/github/bettercap/bettercap/jobs/767382970

`
...
...
Updating Homebrew
$ rvm $brew_ruby do brew update 1>/dev/null
==> Downloading https://ghcr.io/v2/homebrew/portable-ruby/portable-ruby/blobs/sha256:b065e5e3783954f3e65d8d3a6377ca51649bfcfa21b356b0dd70490f74c6bd86
######################################################################## 100.0%
==> Pouring portable-ruby-2.6.3_2.yosemite.bottle.tar.gz
==> Homebrew is run entirely by unpaid volunteers. Please consider donating:
  https://github.com/Homebrew/brew#donations
Updated 2 taps (homebrew/cask and homebrew/core).
==> java has been moved to Homebrew.
To uninstall the cask, run:
  brew uninstall --cask --force java
==> Installing java...
Warning: You are using macOS 10.13.
We (and Apple) do not provide support for this old version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
old version.
Warning: Your Xcode (9.4.1) is outdated.
Please update to Xcode 10.1 (or delete it).
Xcode can be updated from the App Store.
Warning: A newer Command Line Tools release is available.
Update them from Software Update in the App Store or run:
  softwareupdate --all --install --force
If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install
Alternatively, manually download them from:
  https://developer.apple.com/download/more/.
Warning: Your Xcode (9.4.1) is outdated.
Please update to Xcode 10.1 (or delete it).
Xcode can be updated from the App Store.
Warning: A newer Command Line Tools release is available.
Update them from Software Update in the App Store or run:
  softwareupdate --all --install --force
If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install
Alternatively, manually download them from:
  https://developer.apple.com/download/more/.
Warning: Your Xcode (9.4.1) is outdated.
Please update to Xcode 10.1 (or delete it).
Xcode can be updated from the App Store.
Warning: A newer Command Line Tools release is available.
Update them from Software Update in the App Store or run:
  softwareupdate --all --install --force
If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install
Alternatively, manually download them from:
  https://developer.apple.com/download/more/.
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated`

**Comment by evilsocket** [comment] 2021-05-11 10:20
@caquino any idea?

**Comment by evilsocket** [comment] 2021-05-14 12:52
this is caused by the fact that travis defaults to an EOL macOS image, meaning that homebrew needs to compile every package on brew update, which is causing the build timeout.

**Closed** 2021-05-14 12:51 UTC
