### ISSUE TITLE
 SIOCGIWPRIV: Argument list too long, interface might already be monitoring while trying to use bettercap

### ISSUE THREAD

**Issue by Zetlin** [bettercap/bettercap#834] opened 2021-02-17 21:51 UTC
### Environment

Distributor ID:	Kali
Description:	Kali GNU/Linux Rolling
Release:	2020.4
Codename:	kali-rolling
root@LaserJet5700:/home/tester#

Bettercap-2.29-0kali1

### Steps to Reproduce

sudo bettercap -iface wlan0
wifi.recon on

**Expected behavior:** *What you expected to happen*
Should state that wlan0 is in monitor mode 

**Actual behavior:** *What actually happened*
WiFi error while activating handle: Error: wlan0: SIOCGIWPRIV: Argument list too long, interface might already be monitoring. retrying!

I've tried the fix stated here : https://github.com/bettercap/bettercap/issues/614 ; however, both the most recent rtl8812au driver and the 5.20.2 driver cause errors. 

Wifi Adapter I'm using Realtek Semiconductor Corp. Realtek 8812AU/8821AU 802.11ac WLAN Adapter [USB Wireless Dual-Band Adapter 2.4/5Ghz]

**Comment by eklonsousa** [comment] 2021-03-08 15:22
I'm facing the very same issue here.

![Screenshot from 2021-03-08 12-22-26](https://user-images.githubusercontent.com/45145781/110341313-f72dce00-8008-11eb-91fa-b16fdcbc8cc6.png)

**Comment by evilsocket** [comment] 2021-03-23 18:24
little i can do, i think this is either a pcap or driver bug :/

**Comment by curious-ninja** [comment] 2021-04-18 19:40
Is this possibly related to this: 
https://github.com/bettercap/bettercap/issues/819

I’m using AWUS 036ACH, chipset is the same (RTL8812AU), driver rtl88xxau. I have to use libpcap0.8_1.9.1-4, version 1.10.0 doesn’t work for this chipset/driver.

**Comment by evilsocket** [comment] 2021-05-11 10:22
closing as duplicate of https://github.com/bettercap/bettercap/issues/819

**Closed by evilsocket** 2021-05-11 10:22 UTC
Labels: hardware issue
