### ISSUE TITLE
could not set interface wlan0 txpower to 30, 'Set Tx Power' requests not supported

### ISSUE THREAD

**Issue by swapsakker** [bettercap/bettercap#675] opened 2019-12-20 10:51 UTC
**When trying to enable wifi.recon i get this message:**
"could not set interface wlan0 txpower to 30, 'Set Tx Power' requests not supported"

**And when i try to update ui or caplets i get this:**
"this command is inactive in Kali. Install the Kali package bettercap-caplets to get the caplets"

**Running this version:**

UI Version | 1.1.0  requires API 2.20
API version: 2.26.1  compiled with go1.13.3 for linux amd64

**Comment by buffermet** [comment] 2019-12-22 09:46
Possible duplicate of https://github.com/bettercap/bettercap/issues/666, https://github.com/bettercap/bettercap/issues/629, https://github.com/bettercap/bettercap/issues/614

This is also an incomplete issue...

You can manually set the txpower with `sudo iw set wlan0 txpower fixed 3000`

I'm assuming everything is working fine apart from the change in txpower, which is not fatal.

**Closed by buffermet** 2019-12-22 09:46 UTC

**Comment by 3skr0** [comment] 2020-01-12 21:46
`iw wlan0 set txpower fixed 3000`

**Comment by larkwiot** [comment] 2024-12-10 17:07
> I'm assuming everything is working fine apart from the change in txpower, which is not fatal.

It is fatal in the UI. When it fails to set TxPower it does not start the wifi module

**Comment by buffermet** [comment] 2024-12-11 10:03
> It is fatal in the UI. When it fails to set TxPower it does not start the wifi module

Please write a complete issue with all the requested info

**Comment by log1cb0mber** [comment] 2024-12-15 10:23
i also have the same issue on Debian 12 for brostrend ac1200 and bettercap 2.24.1

**Comment by buffermet** [comment] 2024-12-19 11:38
None of you have provided `-debug` output, so we can't help you...
