### ISSUE TITLE
sslstripping is missing on the 2.x version

### ISSUE THREAD

**Issue by larsveelaert** [bettercap/bettercap#154] opened 2018-03-07 14:27 UTC
I'm missing the sslstrip functionality? Downgrading HTTPS and HSTS is not on by default?

**Comment by alexmozzhakov** [comment] 2018-03-07 14:39
You can do it by running sslstrip simultaneously with proper setup of port forwarding and `arp.spoof` module.

**Comment by larsveelaert** [comment] 2018-03-07 14:42
The previous bettercap version had a fully functioning sslstrip+ and reverse dns server built in.
Don't get me wrong, I use the tool a lot, I want to brag about the new version even more if it would have ported this previous functionality also!

**Comment by evilsocket** [comment] 2018-03-07 15:42
sslstripping was not ported to this new version for one simple reason: HSTS ... I don't know your usecases, but in mine sslstrip doesn't work 99% of the times. Is there a good reason to put efforts on that?

**Comment by larsveelaert** [comment] 2018-03-07 16:18
I use your tool in demos on HTTPS and HSTS. It downgrades 70 procent of my clients sites.
It is a great tool to batch-check sites if they are compliant and get awareness up..

I use the legacy version for the time being, but better performance is always nice.

**Comment by evilsocket** [comment] 2018-03-07 16:26
Good point actually ... ok, I'll work on it :) it's not that complicated anyway :)

**Comment by larsveelaert** [comment] 2018-03-07 16:31
For you it is not. You are awesome dude! :p

**Comment by evilsocket** [comment] 2018-03-09 11:14
@larsveelaert feature has been implemented and merget to master, it is enabled by default for both `http.proxy` and `https.proxy` modules, would you mind testing it a little bit? :)

**Comment by leonardoporpora** [comment] 2018-03-09 11:19
I will test it too.

**Comment by larsveelaert** [comment] 2018-03-09 11:23
It would be an honor

**Comment by alexmozzhakov** [comment] 2018-03-09 11:30
@evilsocket As for me no HSTS bypass and HTTP is being redirected to https.
Log says `Sending expired cookies`

**Comment by evilsocket** [comment] 2018-03-09 11:35
@alexmozzhakov I asked @larsveelaert because I need his specific use cases, HSTS is not supposed to be bypassed anymore so as far as I'm concerned your comment is intended behaviour.

**Comment by alexmozzhakov** [comment] 2018-03-09 11:37
@evilsocket regular sslstrip stays on http version. sslstrip+ gives redirect to webm.vk.com

**Comment by evilsocket** [comment] 2018-03-09 11:38
@alexmozzhakov if your browser already cached the HSTS rule for vk.com that's not gonna work

**Comment by alexmozzhakov** [comment] 2018-03-09 11:39
@evilsocket That's why I do it in private mode, omfg

**Comment by evilsocket** [comment] 2018-03-09 11:39
@alexmozzhakov I don't remember asking your help for this feature, what's the `omfg` about?

**Comment by alexmozzhakov** [comment] 2018-03-09 11:43
@evilsocket stop being a dick. U put 👍 to leonardoporpora, so why being rude to me?

**Comment by evilsocket** [comment] 2018-03-09 11:45
Regarding the `PS "specific use cases"? wtf`:

> It downgrades 70 procent of my clients sites.

I was having a conversation with a specific user and asked him to debug this feature with his specific use cases (since he was the one to ask this feature to be ported in the first place).

I'm being "a dick" because this is not the first time you jump in and just give random feedback nobody asked. I politely explained why the feedback is not useful:

>  I need his specific use cases, HSTS is not supposed to be bypassed anymore so as far as I'm concerned your comment is intended behaviour.

Not my fault if you just don't seem able to understand what you're supposed to read before talking.

**Comment by alexmozzhakov** [comment] 2018-03-09 11:49
@evilsocket Well, I'm pretty much concerned that such behavior is unintended, that's why I write it. I'm not talking about preloaded HSTS website. I've already written about sslstrip and sslstrip+ behaviors in same conditions. Seems like it's not good enough for you and u just want to take me stupid. Ok, whatever.

**Comment by evilsocket** [comment] 2018-03-09 11:51
Regarding `That's why I do it in private mode, omfg`, most browsers cache HSTS rules on a per-domain basis regardless if you're in incognito mode / private mode, so you're assumption is not just rude, but it's also wrong.

> Seems like it's not good enough for you

Yes, exactly, a couple of unsolicited log lines about a use case I'm not interested at the moment is defenitely not good enough, so please stop.

I already wasted too much time explaining why you're wrong, I won't anymore, next time i'll just ban you from this repo.

**Comment by larsveelaert** [comment] 2018-03-09 12:10
Let's get this conversation to a constructive point again please;
First testing seems good. I tested the 2 side by side.
- Performance improvement on throughput, great.
- HTTPS sites get downgraded
- Some sites that used to be downgraded (HSTS-level?) with a change in dns, respond differently (ex. norton.com)

Commands used for both versions:
**Legacy version:** sudo bettercap -T 10.3.2.232 -I en8 --proxy
**Awesome version:** sudo bettercap-ng -iface en8 -eval "set arp.spoof.targets 10.3.2.232; http.proxy on; https.proxy on; arp.spoof on"

_Note: Tested on a single target, will continue testing in a controlled enviroment with multiple targets for a measured throughput difference/issues on scale_

**Comment by evilsocket** [comment] 2018-03-09 12:12
@larsveelaert I'd be great if you could indicate me some HTTP page against which the old implementation of th sslstrip still works, so I can compare until I get it working.

**Comment by evilsocket** [comment] 2018-03-09 12:32
![23944](https://user-images.githubusercontent.com/86922/37207665-482dd2e8-239e-11e8-9b3e-41cd5eab95a9.jpg)

Meanwhile :D

**Comment by leonardoporpora** [comment] 2018-03-09 12:35
Omg 😎🔝👍

**Comment by evilsocket** [comment] 2018-03-09 12:36
since we have the basic functionality I'll close this issue to signal it has been implemented, guys feel free either to keep writing here or open new issues if bugs n stuff come out, thanks for the feedback and help ^_^

**Closed by evilsocket** 2018-03-09 12:36 UTC
Labels: new feature, request

**Comment by larsveelaert** [comment] 2018-03-09 12:41
I agree, basic functionality is there, so we can improve from here.
Did you change anything in regards to the HSTS? (I gave as example norton.com).

Will investigate further now

**Comment by larsveelaert** [comment] 2018-03-09 12:43
Just realized I forgot the embed the info about norton.com in my original comment. My apologies sir

**Comment by larsveelaert** [comment] 2018-03-09 12:53
Redownloaded from source.
Behavior on "norton.com" is different.
New version:
![screen shot 2018-03-09 at 13 52 17](https://user-images.githubusercontent.com/15248021/37208280-1db47b2c-23a1-11e8-90ae-e68cd74e4ee6.png)

Old version:
![screen shot 2018-03-09 at 13 53 36](https://user-images.githubusercontent.com/15248021/37208324-4c166e9e-23a1-11e8-9c31-e52d00065c28.png)

**Comment by evilsocket** [comment] 2018-03-09 12:59
@larsveelaert what is the page which originally contains norton.com https link?

**Comment by larsveelaert** [comment] 2018-03-09 13:01
I just type in a couple of domains, manually typing "norton.com" into the addressbar will give different results in favour of the old version

**Comment by larsveelaert** [comment] 2018-03-10 13:41
Were you able to confirm this behavior / locate the issue?

**Comment by evilsocket** [comment] 2018-03-11 14:40
@larsveelaert not really, give I just don't use this feature I'll leave it as basic as it is until either I'll have more requests or someone more interested than me will send a PR :)

**Comment by alexmozzhakov** [comment] 2018-03-12 12:43
I've captured regular (302 redirect) vs sslstrip (http) and  http.proxy (https) behavior. Hope this will help understand what's going on and fix an issue. If not, I'll try fixing it myself because despite that this version is very good. 
[http.proxy](https://github.com/bettercap/bettercap/files/1802745/http.proxy.pcap.zip)
[regular_vs_sslstrip](https://github.com/bettercap/bettercap/files/1802714/regular_vs_sslstrip.pcap.zip)

**Comment by larsveelaert** [comment] 2018-03-12 13:02
Checked this behavior on the sites I was targeting, and I think you are right. They all start with a redirect (301 or 302).

**Comment by alexmozzhakov** [comment] 2018-03-15 18:39
Digging a bit deeper, currently, bettercap doesn't do sslstripping for links, which begin with `http://`
For example, `example.com` website links to `http://www.iana.org/domains/example`, but then iana redirects to https version, so relying on an `http://` link isn't just enough.

**Comment by larsveelaert** [comment] 2018-03-16 10:58
@alexmozzhakov Would handling the redirect (3**) solve the complete issue? I've been thinking about writing a filter to handle it myself but haven't got around doing it.

Did you find cases where the HSTS bypass did not work? (was unclear from your previous post)

**Comment by evilsocket** [comment] 2018-03-16 11:05
If that's the probelm, I believe [here](https://github.com/bettercap/bettercap/blob/master/modules/http_proxy_base_sslstriper.go#L303) a check should be added, if the response is a `3**` redirect to a HTTPS url ( by inspecting the `Location` header ), that url needs to be stripped as well like others found in HTML pages.

**Comment by alexmozzhakov** [comment] 2018-03-16 11:35
@evilsocket yes, I was able to get to this part of the code but haven't looked for a `Location` header yet. I was stuck thinking that it gets into a response body and should've been anyway replaced. I will try to address it by inspecting `Location` header, as you've told. Thanks 🙇. 
@larsveelaert As I already told, HSTS it could be bypassed by adding `wwwww` to a link, but http links don't get parsed, which, I guess, should be fixed too. I will try to handle redirects and see if it works.

**Comment by larsveelaert** [comment] 2018-03-16 12:42
@alexmozzhakov Awesome, I'm going to practice my Go-skills so I can contribute to the project

**Comment by alexmozzhakov** [comment] 2018-03-16 13:37
@evilsocket 
 I'm still getting `[err] Could not resolve m.vk.com/: lookup m.vk.com/: no such host` 
The code I've tried:
```
	urls := make(map[string]string, 0)
	if res.StatusCode == 301 || res.StatusCode == 302 {
		log.Info("[%s] Stripped redirect to %s", core.Green("sslstrip"), core.Bold(res.Header.Get("Location")))
		var strippedRedirect = s.processURL(res.Header.Get("Location"))
		urls[res.Header.Get("Location")] = strippedRedirect
		res.Header.Set("Location", strippedRedirect)
	}
```
The website is being redirected to `wmobile.vk.com`, as expected, but no data spoofing done, so I get 404. Any suggestions?

**Comment by evilsocket** [comment] 2018-03-16 14:41
You also have to patch the Host header back to its original, dude just check the rest of the logic

**Comment by alexmozzhakov** [comment] 2018-03-17 12:03
@evilsocket Since I've added it to urls, like so
`	urls[res.Header.Get("Location")] = strippedRedirect`
it should be added, and as u may see it does, for instance, replace host `wwwww.iana.org with www.iana.org`, but somehow DNS lookup fails. Could you help, please?

**Comment by evilsocket** [comment] 2018-03-18 09:35
The host also needs to be added to the HostTracker in order for the [DNS resolution of the stripped domain](https://github.com/bettercap/bettercap/blob/master/modules/http_proxy_base_sslstriper.go#L148) to work.

The idea is:

1. Strip a domain to something.domain.tld
2. Add something.dmain.tld to the HostTracker for resolution.
3. Check Location header and patch it if needed.
4. At this point, all DNS requests to `something.domain.tld` will be handled by the DNS resolver of the module itself.

**Comment by alexmozzhakov** [comment] 2018-03-18 13:16
@evilsocket The thing is, you do track to `range urls`,  and by the time I've added it to `urls` already

**Comment by evilsocket** [comment] 2018-03-24 17:37
Dude, I linked you the code, you need to do [this](https://github.com/bettercap/bettercap/blob/master/modules/http_proxy_base_sslstriper.go#L338), not just adding it to `urls` ...

**Comment by alexmozzhakov** [comment] 2018-03-24 18:42
@evilsocket you do "this" inside
```
	for url, stripped := range urls {
```
But ok, I will try anyway.

**Comment by alexmozzhakov** [comment] 2018-03-25 10:27
@evilsocket Nope still returns
`
Could not resolve https://www.iana.org/domains/reserved: lookup https://www.iana.org/domains/reserved: no such host
`

**Comment by alexmozzhakov** [comment] 2018-03-25 10:30
What I did was 
```

	urls := make(map[string]string, 0)

	if res.StatusCode >= 301 && res.StatusCode <= 308 {
		log.Info("[%s] Stripped redirect to %s", core.Green("sslstrip"), core.Bold(res.Header.Get("Location")))
		strippedRedirect := s.processURL(res.Header.Get("Location"))
		originalRedirect := res.Header.Get("Location")
		s.hosts.Track(originalRedirect, strippedRedirect)
		urls[originalRedirect] = strippedRedirect
		res.Header.Set("Location", strippedRedirect)
	}
```
[here](https://github.com/bettercap/bettercap/blob/master/modules/http_proxy_base_sslstriper.go#L303)

**Comment by evilsocket** [comment] 2018-03-25 10:34
Again, I'm not interested in developing this feature further than this as I already explained. This means I'm not investing time or efforts in it, because I'd rather invest it in other, IMO more important features.

You're basically asking for an interactive, one on one debug and coding session (since a few days now), don't push me to be rude as usual, understand what I'm saying and respect it.

**Comment by evilsocket** [comment] 2018-03-27 12:47
@alexmozzhakov check this last commit, it's a start but needs some debugging and fixing.

**Comment by alexmozzhakov** [comment] 2018-03-27 13:30
@evilsocket thanks so much. as for now, it doesn't seem to work as expected. I will compare your changes to my local GIT repo and try to work on it. 
Just several thoughts:
* I think that the redirect change should be done by checking whether Location is empty, not by response code (for whatever strange server response configs, it also may not work with clients3.google.com/generate_204, for example, as expected.
* 201 response uses location header for a different reason, according to RFC 7231 and it can cause some problems https://github.com/bettercap/bettercap/blob/ea31346e3e700858fa755c7638d1db1d0aba6498/modules/http_proxy_base_sslstriper.go#L327
so I doubt to make a  `!= 201 check`). 
* Location path may be relative, according to the same RFC, and we may want to check it not to cause any runtime errors. 

I will refactor the code and submit the PR as soon as it will be stable enough for general usage.

**Comment by nirlandau** [comment] 2018-03-30 10:40
I’m not sure whether my setup is not ok, I’m not using it correctly or there is a bug — but I can’t get the sslstrrip to work.

When using the standalone sslstrip program I can downgrade some sites (e.g. hackforum.net :) )

But with bettercap its not working and it continues to the https version of the site.

I am using bettercap v 2.4 on Ubuntu 14.04
Running:
sudo bettercap -iface wlan6 -eval "set http.proxy.sslstrip true; http.proxy on;" (tried to add http**s**.proxy on, got warning page on every url even regular http)
(i.e. I don't need arp because I am the Access Point (hostapd) on wlan6).

**Comment by alexmozzhakov** [comment] 2018-04-03 19:20
Disclaimer: works on my machine, no tests were written before submission.

@evilsocket Look at the solution 😄. However, I would like to ask you some questions about the module if you'll have some time, though. (i.e using `wwwww` over `wwww`)
@larsveelaert It's not very well tested (and writing a test would be a pain in the ass), so I will appreciate your help on it. I've checked the norton example and if you try to access de.norton.com u get it HTTP, but if you try norton.com u will get HTTPS, let me know if it worked before. 

I believe this tool still has a place for improvement and I will appreciate any help.

**Comment by nirlandau** [comment] 2018-04-04 08:57
**@alexmozzhakov** as I checked, many sites that worked with the previous version, don't work now.
did you get a chance to improve this feature?

**Comment by alexmozzhakov** [comment] 2018-04-04 09:12
@nirlandau can you give me an example? did you check the very latest commit?

**Comment by nirlandau** [comment] 2018-04-05 05:52
@alexmozzhakov i am always installing with "go get -u..." so I suppose I am using the latest version (am I?)
two examples:
hackforums.net - the captcha is getting weird and after that it continues to https version
sourceforge.net - also doesn't work at all (continues to https version)
both sites are working in the old bettercap version (1.6.2)

**Comment by alexmozzhakov** [comment] 2018-04-05 08:18
@nirlandau No, you aren't. The PR, as you may have seen, wasn't merged without any explanation.

**Comment by nirlandau** [comment] 2018-04-07 19:30
@alexmozzhakov So I’ve used your version of the sslstrip module and the outcome is the same.
What you showed me (with the printscreen) is not the problem. That I also get with evilsocket’s version. The problem is when trying to login with usr/pass. Then it goes to the https site.

And hackforums is not http by default, especially when you try to login or even just pass the captcha. It goes to https version.

You should check again. With usr/pass. You’ll see different results than bettercap 1.6.2.

**Comment by yungtravla** [comment] 2018-04-08 03:46
I'm working on a SSL & HSTS downgrade module that will allow you to set custom rules for individual hosts. It's hard to make a single script that takes care of everything, as the browser has built-in rules to enforce HTTPS, and hosts can use javascript to ensure the use of HTTPS.

These measures tend to change over time, so the method of attack would need to be updated regularly.

The caplet for this module will look something like this:

```sh
# Choose which hosts should be stripped from SSL protocol (comma separated, wildcards allowed)
set hstsbypass.striphosts t-mobile.at,*.t-mobile.at

# Choose a name for your targeted hosts to bypass their HSTS (comma separated)
set hstsbypass.targets facebook

# Choose the phishing host for each name you have chosen (comma separated, wildcards allowed) (targethost.com,*.targethost.com->replacement.com)
set hstsbypass.phishinghost.facebook    "facebook.com,*.facebook.com -> facedook.com"
set hstsbypass.phishinghost.facebookcdn "static.xx.fbcdn.net         -> static.xx.fbcnd.net"

# Choose potential typos which can be used as a host replacement (comma separated, wildcards allowed)
set hstsbypass.typohosts.facebook facbeook.com,*.facbeook.com,facebook.co,*.facebook.co

# Choose which hosts will no longer be stripped/bypassed for a client after this client's first POST request (comma separated, wildcards allowed)
set hstsbypass.stopafterpost t-mobile.at,*.t-mobile.at,t-derp.at

# Choose paths of scripts to be injected into your targeted hosts (comma separated)
set hstsbypass.injections.facebook ~/caplets/hstsbypass/facebook/patch-blocked-content.js

# Choose the place where each script will be injected relative to the original body (comma separated) (preposition:condition:code) or (preposition:code) or (index)
#   Usage:
#     (after a script containing code)  after:containing:/regexp/
#     (before code in a js file)        before:js:/regexp/
#     (after code in a html file)       after:html:/regexp/
#     (before code in any file)         before:/regexp/
#     (before first script)             0
#     (after first script)              1
#     (after second script)             2
#     (after last script)               -1
set hstsbypass.injectpoint.facebook before:html:/\<\/html\>/i

# Choose which paths are blocked on your targeted hosts (comma separated, wildcards allowed)
set hstsbypass.rejectpaths.facebook /assets/js/anti-phishing/*

# Choose the snippets of code in a script which will block that script on your targeted hosts (comma separated, regexp values)
set hstsbypass.rejectcode.facebook /forceHTTPS\(\)/,/checkLocation\(protocol,host,path,params\)/

# Choose the snippets of code to be replaced by your own (comma separated) (/regexp/->replacement,/regexp/->replacement)
# set hstsbypass.replacecode.facebook "/function.{1,999999}?\(.{1,999999}?\).{1,999999}?\{.{1,999999}?\n{1,999999}?.{1,999999}?\.indexOf\(\"http\:\"\)\>\=0\?.{1,999999}?self\.location\=\"https\:\/\/.{1,999999}?\"\:\'\'\}/ -> console.log(\"Randomized script removed.\");"
```

**Comment by alexmozzhakov** [comment] 2018-04-08 04:07
@yungtravla wow, looking forward for it

**Comment by nirlandau** [comment] 2018-04-08 04:25
@yungtravla that is a great idea! Also looking forward for it.
Meanwhile, I hoped that the current version should at least work as good (if not better) than the previous one. The sites I gave as examples are just two sites I gave that are working with 1.6.2. I can give many more examples so this is something fundamentally different between the versions (although what you said is obviously also true). 
Understanding the differences might help to build a more robust attack. Just a thought.

**Comment by alexmozzhakov** [comment] 2018-04-08 04:33
@nirlandau quick question just to be sure, did it show `(advanced stripping)` near version when you ran it?

**Comment by yungtravla** [comment] 2018-04-08 04:48
@nirlandau this is because browsers are updated. Like I said it's hard to do this all with one script for all hosts.

**Comment by nirlandau** [comment] 2018-04-08 06:31
@alexmozzhakov I tried installing your repo like you said but errors occurred (missing gatt and others), and for some reason it also asked me my github credentials...
so I just diff the files and saw that the only differences are the sslstrip module and the print “advanced sslstrip” in main.go, so I just took these files and compiled it again. Another reason I know it is your version is that I get wwww instead of wwwww (one of your small changes).

@yungtravla  Again, I understand what you are saying but I am talking about the same host, same browser (same setup) but 2 different bettercap versions.
I’ll try to dig more into it...

**Comment by yungtravla** [comment] 2018-04-08 06:39
@nirlandau are you DNS spoofing in the latest version?

**Comment by nirlandau** [comment] 2018-04-08 08:08
@yungtravla I tried both with and without DNS spoofing. no go.
just so I understand, you tried and it was successful?

**Comment by yungtravla** [comment] 2018-04-08 08:13
@nirlandau Nope, I don't really use SSLstrip, but in the legacy version I did some tweaks and managed to get specific hosts to be HSTS downgraded and behave exactly as I wanted. I will post some modules shortly.

**Comment by alexmozzhakov** [comment] 2018-04-08 08:15
@yungtravla Do you plan to work on fixes for nirlandau? Just to be sure that I won’t do a double job 😌?

**Comment by yungtravla** [comment] 2018-04-08 11:36
@alexmozzhakov the module will let you take care of everything

**Comment by alexmozzhakov** [comment] 2018-04-08 15:14
@yungtravla yeah, as far as I know, `wwww` is used to bypass HSTS set to `www.example.com` and `example.com`, but not subdomains, but it didn't work for some reason with `wwww.gmail.com`, so I'm not sure for up-to-date browsers. 🤔

**Comment by nirlandau** [comment] 2018-04-10 07:47
I was trying to understand the difference between the two versions but I couldn’t put my finger on it.
However, I saw many undesirable outcomes that I think would not even be solved by @yungtravla caplet (The caplet is a perfect way to overcome security for the major common sites (e.g. google, Facebook, Twitter etc..) but you don’t expect me to put every site there is out there in it, right?)

When working on average/small/simple sites, sometimes things tend to get ugly.

Just for example: the site fans.com appearance with the different versions: (with or without dns spoof)

(bettercap 1.6.2)
![img_0101](https://user-images.githubusercontent.com/10527698/38543060-2af5f300-3cac-11e8-8bcf-f8e2e9d20192.PNG)

(bettercap 2.4 with @alexmozzhakov update)
![img_0100](https://user-images.githubusercontent.com/10527698/38543045-23c7df44-3cac-11e8-8242-1296926b9498.PNG)

Is there any chance I am missing something?

**Comment by alexmozzhakov** [comment] 2018-04-10 08:43
@nirlandau yeah, it’s still very imperfect and I’m aware of the issue. The difference was described in a simple way on my PR

**Comment by yungtravla** [comment] 2018-04-10 09:13
@nirlandau if you had read the proposed caplet properly, you would have known that you can use a wildcard in the SSLstrip targets... So no, I don't expect you to do anything, but I'm trying to build something that will allow you to do anything.

Just bear with me please, I am currently working on 3 other modules. I don't know how many screenshots you guys want to keep posting describing the exact same issue, but as far as I'm concerned this discussion has been longer than it needs to be. You can tweak around with the current version, make your own module, or wait for me to finish it.

**Comment by nirlandau** [comment] 2018-05-06 06:13
@yungtravla did you by any chance finished working on your strip caplet?

**Comment by yungtravla** [comment] 2018-05-06 06:57
@nirlandau I think so, about to start tests.

**Comment by yungtravla** [comment] 2018-06-08 02:17
Just submitted a PR :)
